
package com.deppon.esb.esbtogis;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-05-02T14:57:49.312+08:00
 * Generated source version: 2.7.3
 * 
 */
public final class GisService_GisServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.deppon.com/gis/gisService", "gisService");

    private GisService_GisServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GisService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GisService_Service ss = new GisService_Service(wsdlURL, SERVICE_NAME);
        GisService port = ss.getGisServiceSOAP();  
        
        {
        System.out.println("Invoking queryCoordinate...");
        com.deppon.esb.esbtogis.QueryDeptCoordinateRequest _queryCoordinate_queryDeptCoordinateRequest = null;
        com.deppon.esb.esbtogis.ESBHeader _queryCoordinate_esbHeaderVal = null;
        javax.xml.ws.Holder<com.deppon.esb.esbtogis.ESBHeader> _queryCoordinate_esbHeader = new javax.xml.ws.Holder<com.deppon.esb.esbtogis.ESBHeader>(_queryCoordinate_esbHeaderVal);
        try {
            com.deppon.esb.esbtogis.QueryDeptCoordinateResponse _queryCoordinate__return = port.queryCoordinate(_queryCoordinate_queryDeptCoordinateRequest, _queryCoordinate_esbHeader);
            System.out.println("queryCoordinate.result=" + _queryCoordinate__return);

            System.out.println("queryCoordinate._queryCoordinate_esbHeader=" + _queryCoordinate_esbHeader.value);
        } catch (CommonException e) { 
            System.out.println("Expected exception: commonException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
