package com.deppon.esb.esbtogis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * 查询部门坐标
 *
 * This class was generated by Apache CXF 2.7.3
 * 2013-05-02T14:57:49.421+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://www.deppon.com/gis/gisService", name = "gisService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GisService {

    @WebResult(name = "queryDeptCoordinateResponse", targetNamespace = "http://www.deppon.com/deppon/gis/inteface/domain", partName = "queryDeptCoordinateResponse")
    @WebMethod(action = "http://www.deppon.com/gis/gisService/queryCoordinate")
    public QueryDeptCoordinateResponse queryCoordinate(
        @WebParam(partName = "queryDeptCoordinateRequest", name = "queryDeptCoordinateRequest", targetNamespace = "http://www.deppon.com/deppon/gis/inteface/domain")
        QueryDeptCoordinateRequest queryDeptCoordinateRequest,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader
    ) throws CommonException;
}
