package com.deppon.esb.esbtogis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-05-02T14:57:49.421+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "gisService", 
                  wsdlLocation = "file:/D:/Java_Programs/workspace/CRM_QUERY_DPETCOORDINATES/gisService.wsdl",
                  targetNamespace = "http://www.deppon.com/gis/gisService") 
public class GisService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.deppon.com/gis/gisService", "gisService");
    public final static QName GisServiceSOAP = new QName("http://www.deppon.com/gis/gisService", "gisServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Java_Programs/workspace/CRM_QUERY_DPETCOORDINATES/gisService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GisService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Java_Programs/workspace/CRM_QUERY_DPETCOORDINATES/gisService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GisService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GisService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GisService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GisService
     */
    @WebEndpoint(name = "gisServiceSOAP")
    public GisService getGisServiceSOAP() {
        return super.getPort(GisServiceSOAP, GisService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GisService
     */
    @WebEndpoint(name = "gisServiceSOAP")
    public GisService getGisServiceSOAP(WebServiceFeature... features) {
        return super.getPort(GisServiceSOAP, GisService.class, features);
    }

}
