
package com.deppon.foss.waybill;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-03-25T14:05:53.390+08:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "commonExceptionInfo", targetNamespace = "http://www.deppon.com/esb/exception")
public class CommonException extends Exception {
    
    private com.deppon.foss.waybill.CommonExceptionInfo commonExceptionInfo;

    public CommonException() {
        super();
    }
    
    public CommonException(String message) {
        super(message);
    }
    
    public CommonException(String message, Throwable cause) {
        super(message, cause);
    }

    public CommonException(String message, com.deppon.foss.waybill.CommonExceptionInfo commonExceptionInfo) {
        super(message);
        this.commonExceptionInfo = commonExceptionInfo;
    }

    public CommonException(String message, com.deppon.foss.waybill.CommonExceptionInfo commonExceptionInfo, Throwable cause) {
        super(message, cause);
        this.commonExceptionInfo = commonExceptionInfo;
    }

    public com.deppon.foss.waybill.CommonExceptionInfo getFaultInfo() {
        return this.commonExceptionInfo;
    }
}
