package com.deppon.foss.waybill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-03-25T14:05:53.390+08:00
 * Generated source version: 2.6.2
 *
 */
@WebService(targetNamespace = "http://www.deppon.com/foss/waybillService", name = "WaybillService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WaybillService {

    @WebResult(name = "QueryDetailResponse", targetNamespace = "http://www.deppon.com/esb/inteface/domain/waybillService", partName = "payload")
    @WebMethod(action = "http://www.deppon.com/foss/customerService/queryDetail")
    public QueryDetailResponse queryDetail(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "payload", name = "QueryDetailRequest", targetNamespace = "http://www.deppon.com/esb/inteface/domain/waybillService")
        QueryDetailRequest payload
    ) throws CommonException;
}
