package com.deppon.crm.module.customer.server.util;

import javax.sql.DataSource;

import junit.framework.TestCase;

import org.junit.Test;

import com.deppon.crm.module.authorization.server.dao.IUserDao;
import com.deppon.crm.module.authorization.server.dao.impl.UserDao;
import com.deppon.crm.module.common.server.manager.ITodoWorkflowManager;
import com.deppon.crm.module.common.server.manager.impl.TodoWorkflowManager;
import com.deppon.crm.module.customer.server.dao.IAlterMemberDao;
import com.deppon.crm.module.customer.server.dao.IApprovingWokflowDataDao;
import com.deppon.crm.module.customer.server.dao.IBaseDataDao;
import com.deppon.crm.module.customer.server.dao.IChangeMemberDeptDao;
import com.deppon.crm.module.customer.server.dao.IContactDao;
import com.deppon.crm.module.customer.server.dao.IContactIntegralDao;
import com.deppon.crm.module.customer.server.dao.IContactVaryDao;
import com.deppon.crm.module.customer.server.dao.IContractDao;
import com.deppon.crm.module.customer.server.dao.IContractWorkflowDao;
import com.deppon.crm.module.customer.server.dao.ICustCreditDao;
import com.deppon.crm.module.customer.server.dao.IExamineRecordDao;
import com.deppon.crm.module.customer.server.dao.IGiftDao;
import com.deppon.crm.module.customer.server.dao.IGoodTradeMappingDao;
import com.deppon.crm.module.customer.server.dao.IIntegRuleDao;
import com.deppon.crm.module.customer.server.dao.IIntegralDao;
import com.deppon.crm.module.customer.server.dao.IMemberDao;
import com.deppon.crm.module.customer.server.dao.IMemberIntegralDao;
import com.deppon.crm.module.customer.server.dao.IRewardIntegRuleDao;
import com.deppon.crm.module.customer.server.dao.IWaybillIntegralDao;
import com.deppon.crm.module.customer.server.dao.IWorkFlowDao;
import com.deppon.crm.module.customer.server.dao.impl.AlterMemberDao;
import com.deppon.crm.module.customer.server.dao.impl.ApprovingWorkflowDataDao;
import com.deppon.crm.module.customer.server.dao.impl.BaseDataDao;
import com.deppon.crm.module.customer.server.dao.impl.ChangeMemberDeptDao;
import com.deppon.crm.module.customer.server.dao.impl.ContactDao;
import com.deppon.crm.module.customer.server.dao.impl.ContactIntegralDao;
import com.deppon.crm.module.customer.server.dao.impl.ContactVaryDao;
import com.deppon.crm.module.customer.server.dao.impl.ContractDao;
import com.deppon.crm.module.customer.server.dao.impl.ExamineRecordDao;
import com.deppon.crm.module.customer.server.dao.impl.GiftDao;
import com.deppon.crm.module.customer.server.dao.impl.IntegRuleDao;
import com.deppon.crm.module.customer.server.dao.impl.IntegralDao;
import com.deppon.crm.module.customer.server.dao.impl.MemberDao;
import com.deppon.crm.module.customer.server.dao.impl.MemberIntegralDao;
import com.deppon.crm.module.customer.server.dao.impl.RewardIntegRuleDao;
import com.deppon.crm.module.customer.server.dao.impl.WaybillIntegralDao;
import com.deppon.crm.module.customer.server.dao.impl.WorkFlowDao;
import com.deppon.crm.module.customer.server.manager.ContractValidator;
import com.deppon.crm.module.customer.server.manager.CustomerValidator;
import com.deppon.crm.module.customer.server.manager.IAlterMemberManager;
import com.deppon.crm.module.customer.server.manager.IBaseDataManager;
import com.deppon.crm.module.customer.server.manager.IChangeMemberDeptManager;
import com.deppon.crm.module.customer.server.manager.IContactManager;
import com.deppon.crm.module.customer.server.manager.IContractManager;
import com.deppon.crm.module.customer.server.manager.IIntegralManager;
import com.deppon.crm.module.customer.server.manager.IMemberManager;
import com.deppon.crm.module.customer.server.manager.IWaybillIntegralManager;
import com.deppon.crm.module.customer.server.manager.impl.AlterMemberManager;
import com.deppon.crm.module.customer.server.manager.impl.BaseDataManager;
import com.deppon.crm.module.customer.server.manager.impl.ChangeMemberDeptManager;
import com.deppon.crm.module.customer.server.manager.impl.ContactManager;
import com.deppon.crm.module.customer.server.manager.impl.ContractManager;
import com.deppon.crm.module.customer.server.manager.impl.IntegRuleManager;
import com.deppon.crm.module.customer.server.manager.impl.IntegralManager;
import com.deppon.crm.module.customer.server.manager.impl.MemberManager;
import com.deppon.crm.module.customer.server.manager.impl.MemberWorkFlowManager;
import com.deppon.crm.module.customer.server.manager.impl.WaybillIntegralManager;
import com.deppon.crm.module.customer.server.manager.impl.WorkFLowManager;
import com.deppon.crm.module.customer.server.service.IAlterMemberService;
import com.deppon.crm.module.customer.server.service.IApprovingWokflowDataService;
import com.deppon.crm.module.customer.server.service.IBaseDataService;
import com.deppon.crm.module.customer.server.service.IChangeMemberDeptService;
import com.deppon.crm.module.customer.server.service.IContactIntegralService;
import com.deppon.crm.module.customer.server.service.IContactService;
import com.deppon.crm.module.customer.server.service.IContactVaryService;
import com.deppon.crm.module.customer.server.service.IContractService;
import com.deppon.crm.module.customer.server.service.IIntegralService;
import com.deppon.crm.module.customer.server.service.IMemberIntegralService;
import com.deppon.crm.module.customer.server.service.IMemberService;
import com.deppon.crm.module.customer.server.service.IWaybillIntegralService;
import com.deppon.crm.module.customer.server.service.impl.AlterMemberService;
import com.deppon.crm.module.customer.server.service.impl.ApprovingWokflowDataService;
import com.deppon.crm.module.customer.server.service.impl.BaseDataService;
import com.deppon.crm.module.customer.server.service.impl.ChangeMemberDeptService;
import com.deppon.crm.module.customer.server.service.impl.ContactIntegralService;
import com.deppon.crm.module.customer.server.service.impl.ContactService;
import com.deppon.crm.module.customer.server.service.impl.ContactVaryService;
import com.deppon.crm.module.customer.server.service.impl.ContractService;
import com.deppon.crm.module.customer.server.service.impl.ExamineRecordService;
import com.deppon.crm.module.customer.server.service.impl.IntegralService;
import com.deppon.crm.module.customer.server.service.impl.MemberIntegralService;
import com.deppon.crm.module.customer.server.service.impl.MemberService;
import com.deppon.crm.module.customer.server.service.impl.WaybillIntegralService;
import com.deppon.crm.module.custrepeat.server.dao.IRepeatedCustDao;
import com.deppon.crm.module.custrepeat.server.manager.IRepeatedCustManager;
import com.deppon.foss.framework.entity.IUser;

public class BeanUtil extends TestCase{
	public IUser marking,crDept,bizManager,create,region,neighborhood,cause;
	
	public static IBaseDataManager  baseDataManager = null;
	public static IChangeMemberDeptManager changeMemberDeptManager = null;
	public static IContactManager contactManager = null;
	public static IContractManager contractManager = null;
	public static IIntegralManager integralManager = null;
	public static IIntegralManager inIIntegralManager = null;
	public static IntegRuleManager integRuleManager = null;
	public static IMemberManager  memberManager = null;
	public static MemberWorkFlowManager memberWorkFlowManager = null;
	public static ITodoWorkflowManager  todoWorkflowManager = null;
	public static IWaybillIntegralManager waybillIntegralManager = null;
	public static IAlterMemberManager alterMemberManager = null;
	public static WorkFLowManager workFlowManager = null;
	
	public static IContactVaryService contactVaryService = null;
	public static ExamineRecordService examineRecordService = null;
	public static IIntegralService integralService = null;
	public static IContactService contactService = null;
	public static IApprovingWokflowDataService approvingWokflowDataService = null;
	public static IMemberIntegralService memberIntegralService= null;
	public static IMemberService memberService = null;
	public static IContractService contractService = null;
	public static IAlterMemberService alterMemberService = null;
	public static IBaseDataService baseDataService = null;
	public static IChangeMemberDeptService changeMemberDeptService = null;
	public static IContactIntegralService contactIntegralService = null;
	public static IWaybillIntegralService waybillIntegralService = null;
//	public static MemberEffectValidate memberEffectValidate = null;
	public static CustomerValidator customerValidator = null;
	public static ContractValidator contractValidator = null;
	
	public static IUserDao userDao = null;
	public static IWorkFlowDao workFlowDao = null;
	public static IExamineRecordDao examineRecordDao = null;
	public static IWaybillIntegralDao waybillIntegralDao = null;
	public static IRewardIntegRuleDao rewardIntegRuleDao = null;
	public static IMemberIntegralDao memberIntegralDao = null;
	public static IMemberDao memberDao = null;
	public static IIntegRuleDao integRuleDao = null;
	public static IIntegralDao integralDao = null;
	public static IGiftDao giftDao = null;
	public static IApprovingWokflowDataDao approvingWokflowDataDao = null;
	public static IContactIntegralDao contactIntegralDao = null;
	public static IContactDao contactDao = null;
	public static IAlterMemberDao alterMemberDao = null;
	public static IBaseDataDao baseDataDao = null;
	public static IChangeMemberDeptDao changeMemberDeptDao = null;
	public static IContactVaryDao contactVaryDao = null;
	public static IContractDao contractDao = null;
	public static DataSource dataSource = null;
	
	public static IRepeatedCustDao repeatedCustDao = null;
	public static IRepeatedCustManager repeatedCustManager = null;
	public static IGoodTradeMappingDao goodTradeMappingDao = null;
	public static IContractWorkflowDao contractWorkflowDao = null;
	public static ICustCreditDao custCreditDao = null;
	
	static {
		baseDataManager = SpringTestHelper.getBean(BaseDataManager.class);
		changeMemberDeptManager = SpringTestHelper.getBean(ChangeMemberDeptManager.class);
		contactManager =  SpringTestHelper.getBean(ContactManager.class);
		contactService = SpringTestHelper.getBean(ContactService.class);
		contractManager = SpringTestHelper.getBean(ContractManager.class);
		customerValidator = SpringTestHelper.getBean(CustomerValidator.class);
		approvingWokflowDataService = SpringTestHelper.getBean(ApprovingWokflowDataService.class);
		integralManager =  SpringTestHelper.getBean(IntegralManager.class);
		inIIntegralManager = SpringTestHelper.getBean(IntegralManager.class);
		integRuleManager = SpringTestHelper.getBean(IntegRuleManager.class);
//		memberEffectValidate = SpringTestHelper.getBean(MemberEffectValidate.class);
		memberManager = SpringTestHelper.getBean(MemberManager.class);
		memberWorkFlowManager = SpringTestHelper.getBean(MemberWorkFlowManager.class);
		todoWorkflowManager = SpringTestHelper.getBean(TodoWorkflowManager.class);
		waybillIntegralManager = SpringTestHelper.getBean(WaybillIntegralManager.class);
		contactVaryService = SpringTestHelper.getBean(ContactVaryService.class);
		userDao = SpringTestHelper.getBean(UserDao.class);
		workFlowDao = SpringTestHelper.getBean(WorkFlowDao.class);
		examineRecordDao = SpringTestHelper.getBean(ExamineRecordDao.class);
		examineRecordService = SpringTestHelper.getBean(ExamineRecordService.class);
		integralService = SpringTestHelper.getBean(IntegralService.class);
		memberIntegralService= SpringTestHelper.getBean(MemberIntegralService.class);
		memberService = SpringTestHelper.getBean(MemberService.class);
		waybillIntegralDao = SpringTestHelper.getBean(WaybillIntegralDao.class);
		dataSource = SpringTestHelper.getBean(DataSource.class);
		rewardIntegRuleDao = SpringTestHelper.getBean(RewardIntegRuleDao.class);
		memberIntegralDao = SpringTestHelper.getBean(MemberIntegralDao.class);
		memberDao = SpringTestHelper.getBean(MemberDao.class);
		integRuleDao = SpringTestHelper.getBean(IntegRuleDao.class);
		integralDao = SpringTestHelper.getBean(IntegralDao.class);
		giftDao = SpringTestHelper.getBean(GiftDao.class);
		approvingWokflowDataDao = SpringTestHelper.getBean(ApprovingWorkflowDataDao.class);
		contactIntegralDao = SpringTestHelper.getBean(ContactIntegralDao.class);
		contactDao = SpringTestHelper.getBean(ContactDao.class);
		alterMemberDao = SpringTestHelper.getBean(AlterMemberDao.class);
		baseDataDao = SpringTestHelper.getBean(BaseDataDao.class);
		changeMemberDeptDao = SpringTestHelper.getBean(ChangeMemberDeptDao.class);
		contactVaryDao = SpringTestHelper.getBean(ContactVaryDao.class);
		contractDao = SpringTestHelper.getBean(ContractDao.class);
		contractService = SpringTestHelper.getBean(ContractService.class);
		alterMemberService = SpringTestHelper.getBean(AlterMemberService.class);
		baseDataService = SpringTestHelper.getBean(BaseDataService.class);;
		changeMemberDeptService = SpringTestHelper.getBean(ChangeMemberDeptService.class);
		contactIntegralService = SpringTestHelper.getBean(ContactIntegralService.class);
		waybillIntegralService = SpringTestHelper.getBean(WaybillIntegralService.class);
		alterMemberManager =  SpringTestHelper.getBean(AlterMemberManager.class);
		workFlowManager = SpringTestHelper.getBean(WorkFLowManager.class);
		
		contractValidator = SpringTestHelper.getBean(ContractValidator.class);
		repeatedCustDao = (IRepeatedCustDao)SpringTestHelper.getBean("repeatedCustDao");
		repeatedCustManager = (IRepeatedCustManager) SpringTestHelper.getBean("repeatedCustManager");
		goodTradeMappingDao = (IGoodTradeMappingDao) SpringTestHelper.getBean("goodTradeMappingDao");
		contractWorkflowDao = (IContractWorkflowDao) SpringTestHelper.getBean("ContractWorkflowDao");
		custCreditDao = (ICustCreditDao) SpringTestHelper.getBean("custCreditDao");
	}
	@Test
	public void test(){
		assertTrue(true);
	}
}
