package com.deppon.interfaces.gift;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-07-11T15:45:32.109+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "GiftApplyResultServiceImplService", 
                  wsdlLocation = "http://192.168.17.172:8088/crm/ws/giftApplyResultService?wsdl",
                  targetNamespace = "http://impl.workflow.interfaces.module.crm.deppon.com/") 
public class GiftApplyResultServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.workflow.interfaces.module.crm.deppon.com/", "GiftApplyResultServiceImplService");
    public final static QName GiftApplyResultServiceImplPort = new QName("http://impl.workflow.interfaces.module.crm.deppon.com/", "GiftApplyResultServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.17.172:8088/crm/ws/giftApplyResultService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GiftApplyResultServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.17.172:8088/crm/ws/giftApplyResultService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GiftApplyResultServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GiftApplyResultServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GiftApplyResultServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IGiftApplyResultService
     */
    @WebEndpoint(name = "GiftApplyResultServiceImplPort")
    public IGiftApplyResultService getGiftApplyResultServiceImplPort() {
        return super.getPort(GiftApplyResultServiceImplPort, IGiftApplyResultService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGiftApplyResultService
     */
    @WebEndpoint(name = "GiftApplyResultServiceImplPort")
    public IGiftApplyResultService getGiftApplyResultServiceImplPort(WebServiceFeature... features) {
        return super.getPort(GiftApplyResultServiceImplPort, IGiftApplyResultService.class, features);
    }

}
