package com.deppon.erp.payment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-10-25T16:46:59.906+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "Erp2crmMsgServiceImplService", 
                  wsdlLocation = "http://192.168.17.203:8080/eas2fin/services/erp2crmMsgService?wsdl",
                  targetNamespace = "http://impl.service.amsonline.ws.deppon.com/") 
public class Erp2CrmMsgServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.amsonline.ws.deppon.com/", "Erp2crmMsgServiceImplService");
    public final static QName Erp2CrmMsgServiceImplPort = new QName("http://impl.service.amsonline.ws.deppon.com/", "Erp2crmMsgServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.17.203:8080/eas2fin/services/erp2crmMsgService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Erp2CrmMsgServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.17.203:8080/eas2fin/services/erp2crmMsgService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Erp2CrmMsgServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Erp2CrmMsgServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Erp2CrmMsgServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IErp2CrmMsgService
     */
    @WebEndpoint(name = "Erp2crmMsgServiceImplPort")
    public IErp2CrmMsgService getErp2CrmMsgServiceImplPort() {
        return super.getPort(Erp2CrmMsgServiceImplPort, IErp2CrmMsgService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IErp2CrmMsgService
     */
    @WebEndpoint(name = "Erp2crmMsgServiceImplPort")
    public IErp2CrmMsgService getErp2CrmMsgServiceImplPort(WebServiceFeature... features) {
        return super.getPort(Erp2CrmMsgServiceImplPort, IErp2CrmMsgService.class, features);
    }

}
