
package com.deppon.crm.module.interfaces.channel.domain;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.deppon.crm.module.interfaces.channel.ChannelService;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-29T17:42:39.421+08:00
 * Generated source version: 2.7.3
 * 
 */
public final class ChannelService_ChannelServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.deppon.com/channel/channelService/", "ChannelService");

    private ChannelService_ChannelServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ChannelService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ChannelService_Service ss = new ChannelService_Service(wsdlURL, SERVICE_NAME);
        ChannelService port = ss.getChannelServiceSOAP();  
        
        {
        System.out.println("Invoking channelUpdateWayBillNum...");
        com.deppon.crm.module.interfaces.channel.domain.UpdateWayBillNumRequest _channelUpdateWayBillNum_request = null;
        com.deppon.crm.module.interfaces.channel.domain.ESBHeader _channelUpdateWayBillNum_esbHeaderVal = null;
        javax.xml.ws.Holder<com.deppon.crm.module.interfaces.channel.domain.ESBHeader> _channelUpdateWayBillNum_esbHeader = new javax.xml.ws.Holder<com.deppon.crm.module.interfaces.channel.domain.ESBHeader>(_channelUpdateWayBillNum_esbHeaderVal);
        try {
            com.deppon.crm.module.interfaces.channel.domain.UpdateWayBillNumResponse _channelUpdateWayBillNum__return = port.channelUpdateWayBillNum(_channelUpdateWayBillNum_request, _channelUpdateWayBillNum_esbHeader);
            System.out.println("channelUpdateWayBillNum.result=" + _channelUpdateWayBillNum__return);

            System.out.println("channelUpdateWayBillNum._channelUpdateWayBillNum_esbHeader=" + _channelUpdateWayBillNum_esbHeader.value);
        } catch (CommonException e) { 
            System.out.println("Expected exception: CommonException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
