package com.deppon.oa.error;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-07T21:07:23.268+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.primeton.com/ErrorService", name = "ErrorService")
@XmlSeeAlso({ObjectFactory.class})
public interface ErrorService {

    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/ErrorService")
    @RequestWrapper(localName = "getErrorInfo", targetNamespace = "http://www.primeton.com/ErrorService", className = "com.deppon.oa.error.GetErrorInfo")
    @WebMethod
    @ResponseWrapper(localName = "getErrorInfoResponse", targetNamespace = "http://www.primeton.com/ErrorService", className = "com.deppon.oa.error.GetErrorInfoResponse")
    public com.deppon.oa.error.ArrayOfString getErrorInfo(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/ErrorService")
        java.lang.String in0
    );

    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/ErrorService")
    @RequestWrapper(localName = "returnErrosInfor", targetNamespace = "http://www.primeton.com/ErrorService", className = "com.deppon.oa.error.ReturnErrosInfor")
    @WebMethod
    @ResponseWrapper(localName = "returnErrosInforResponse", targetNamespace = "http://www.primeton.com/ErrorService", className = "com.deppon.oa.error.ReturnErrosInforResponse")
    public com.deppon.oa.error.ArrayOfString returnErrosInfor(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/ErrorService")
        java.lang.String in0
    );
}
