insert into t_code_head (FID, FCODETYPE, FCODETYPEDESC, FCREATETIME, FCREATEUSERID, FLASTUPDATETIME, FLASTMODIFYUSERID)
values (400000701, 'MAP_MAKER_STATUS', '地图标记', sysdate, 106138, sysdate, 106138);

insert into t_code_detail (FID, FPARENTID, FCODETYPE, FCODE, FCODEDESC, FSTATUS, FCODESEQ, FLANGUAGE, FCREATETIME, FCREATEUSERID, FLASTUPDATETIME, FLASTMODIFYUSERID)
values (400000702, 0, 'MAP_MAKER_STATUS', 'MAPMAKED', '已经标记', 'A', 1, 'zh_CN', sysdate, 106138, sysdate, 106138);

insert into t_code_detail (FID, FPARENTID, FCODETYPE, FCODE, FCODEDESC, FSTATUS, FCODESEQ, FLANGUAGE, FCREATETIME, FCREATEUSERID, FLASTUPDATETIME, FLASTMODIFYUSERID)
values (400000703, 0, 'MAP_MAKER_STATUS', 'UNMAKER', '未标记', 'A', 2, 'zh_CN', sysdate, 106138, sysdate, 106138);
insert into t_code_detail (FID, FPARENTID, FCODETYPE, FCODE, FCODEDESC, FSTATUS, FCODESEQ, FLANGUAGE, FCREATETIME, FCREATEUSERID, FLASTUPDATETIME, FLASTMODIFYUSERID)
values (400000704, 0, 'MAP_MAKER_STATUS', 'ALL', '全部', 'A', 3, 'zh_CN', sysdate, 106138, sysdate, 106138);
