package com.deppon.lms.workflow;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-07T21:08:25.528+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.primeton.com/IApplyGiftService", name = "IApplyGiftService")
@XmlSeeAlso({ObjectFactory.class})
public interface IApplyGiftService {

    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/IApplyGiftService")
    @RequestWrapper(localName = "applyGift", targetNamespace = "http://www.primeton.com/IApplyGiftService", className = "com.deppon.lms.workflow.ApplyGift")
    @WebMethod
    @ResponseWrapper(localName = "applyGiftResponse", targetNamespace = "http://www.primeton.com/IApplyGiftService", className = "com.deppon.lms.workflow.ApplyGiftResponse")
    public java.lang.String applyGift(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/IApplyGiftService")
        java.lang.String in0
    );
}
