
package com.deppon.oa.workflow;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-07T21:07:23.038+08:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "drawbackWorkFlow_WorkFlowException", targetNamespace = "http://www.primeton.com/WorkFlowService")
public class DrawbackWorkFlowWorkFlowException extends Exception {
    
    private com.deppon.oa.workflow.WorkFlowException drawbackWorkFlowWorkFlowException;

    public DrawbackWorkFlowWorkFlowException() {
        super();
    }
    
    public DrawbackWorkFlowWorkFlowException(String message) {
        super(message);
    }
    
    public DrawbackWorkFlowWorkFlowException(String message, Throwable cause) {
        super(message, cause);
    }

    public DrawbackWorkFlowWorkFlowException(String message, com.deppon.oa.workflow.WorkFlowException drawbackWorkFlowWorkFlowException) {
        super(message);
        this.drawbackWorkFlowWorkFlowException = drawbackWorkFlowWorkFlowException;
    }

    public DrawbackWorkFlowWorkFlowException(String message, com.deppon.oa.workflow.WorkFlowException drawbackWorkFlowWorkFlowException, Throwable cause) {
        super(message, cause);
        this.drawbackWorkFlowWorkFlowException = drawbackWorkFlowWorkFlowException;
    }

    public com.deppon.oa.workflow.WorkFlowException getFaultInfo() {
        return this.drawbackWorkFlowWorkFlowException;
    }
}
