package com.deppon.oa.workflow;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-08-30T19:43:34.765+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "QueryWorkFlowStateServiceService", 
                  wsdlLocation = "http://192.168.19.33:8080/eos-default/QueryWorkFlowStateService?wsdl",
                  targetNamespace = "http://www.primeton.com/QueryWorkFlowStateService") 
public class QueryWorkFlowStateServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.primeton.com/QueryWorkFlowStateService", "QueryWorkFlowStateServiceService");
    public final static QName QueryWorkFlowStateServicePort = new QName("http://www.primeton.com/QueryWorkFlowStateService", "QueryWorkFlowStateServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.19.33:8080/eos-default/QueryWorkFlowStateService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryWorkFlowStateServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.19.33:8080/eos-default/QueryWorkFlowStateService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryWorkFlowStateServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryWorkFlowStateServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryWorkFlowStateServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QueryWorkFlowStateService
     */
    @WebEndpoint(name = "QueryWorkFlowStateServicePort")
    public QueryWorkFlowStateService getQueryWorkFlowStateServicePort() {
        return super.getPort(QueryWorkFlowStateServicePort, QueryWorkFlowStateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryWorkFlowStateService
     */
    @WebEndpoint(name = "QueryWorkFlowStateServicePort")
    public QueryWorkFlowStateService getQueryWorkFlowStateServicePort(WebServiceFeature... features) {
        return super.getPort(QueryWorkFlowStateServicePort, QueryWorkFlowStateService.class, features);
    }

}
