//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.03 at 11:51:09
//


package com.deppon.crm.module.interfaces.uums.jms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.deppon.crm.module.interfaces.uums.jms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendUserInfoDeptAllRequest_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SendUserInfoDeptAllRequest");
    private final static QName _SendUserInfoDeptAllResponse_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SendUserInfoDeptAllResponse");
    private final static QName _SendPositionRequest_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SendPositionRequest");
    private final static QName _SendPositionResponse_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SendPositionResponse");
    private final static QName _SendAdminOrgResponse_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SendAdminOrgResponse");
    private final static QName _SendAdminOrgRequest_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SendAdminOrgRequest");
    private final static QName _SendEmployeeRequest_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SendEmployeeRequest");
    private final static QName _SendEmployeeResponse_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SendEmployeeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deppon.crm.module.interfaces.uums.jms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendEmployeeRequest }
     * 
     */
    public SendEmployeeRequest createSendEmployeeRequest() {
        return new SendEmployeeRequest();
    }

    /**
     * Create an instance of {@link SendEmployeeProcessReult }
     * 
     */
    public SendEmployeeProcessReult createSendEmployeeProcessReult() {
        return new SendEmployeeProcessReult();
    }

    /**
     * Create an instance of {@link EmployeeInfo }
     * 
     */
    public EmployeeInfo createEmployeeInfo() {
        return new EmployeeInfo();
    }

    /**
     * Create an instance of {@link SendEmployeeResponse }
     * 
     */
    public SendEmployeeResponse createSendEmployeeResponse() {
        return new SendEmployeeResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendEmployeeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SendEmployeeRequest")
    public JAXBElement<SendEmployeeRequest> createSendEmployeeRequest(SendEmployeeRequest value) {
        return new JAXBElement<SendEmployeeRequest>(_SendEmployeeRequest_QNAME, SendEmployeeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SendEmployeeResponse")
    public JAXBElement<SendEmployeeResponse> createSendEmployeeResponse(SendEmployeeResponse value) {
        return new JAXBElement<SendEmployeeResponse>(_SendEmployeeResponse_QNAME, SendEmployeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link SendAdminOrgRequest }
     * 
     */
    public SendAdminOrgRequest createSendAdminOrgRequest() {
        return new SendAdminOrgRequest();
    }

    /**
     * Create an instance of {@link AdminOrgInfo }
     * 
     */
    public AdminOrgInfo createAdminOrgInfo() {
        return new AdminOrgInfo();
    }

    /**
     * Create an instance of {@link SendAdminOrgProcessReult }
     * 
     */
    public SendAdminOrgProcessReult createSendAdminOrgProcessReult() {
        return new SendAdminOrgProcessReult();
    }

    /**
     * Create an instance of {@link SendAdminOrgResponse }
     * 
     */
    public SendAdminOrgResponse createSendAdminOrgResponse() {
        return new SendAdminOrgResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendAdminOrgResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SendAdminOrgResponse")
    public JAXBElement<SendAdminOrgResponse> createSendAdminOrgResponse(SendAdminOrgResponse value) {
        return new JAXBElement<SendAdminOrgResponse>(_SendAdminOrgResponse_QNAME, SendAdminOrgResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendAdminOrgRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SendAdminOrgRequest")
    public JAXBElement<SendAdminOrgRequest> createSendAdminOrgRequest(SendAdminOrgRequest value) {
        return new JAXBElement<SendAdminOrgRequest>(_SendAdminOrgRequest_QNAME, SendAdminOrgRequest.class, null, value);
    }
    /**
     * Create an instance of {@link PositionInfo }
     * 
     */
    public PositionInfo createPositionInfo() {
        return new PositionInfo();
    }

    /**
     * Create an instance of {@link SendPositionProcessReult }
     * 
     */
    public SendPositionProcessReult createSendPositionProcessReult() {
        return new SendPositionProcessReult();
    }

    /**
     * Create an instance of {@link SendPositionRequest }
     * 
     */
    public SendPositionRequest createSendPositionRequest() {
        return new SendPositionRequest();
    }

    /**
     * Create an instance of {@link SendPositionResponse }
     * 
     */
    public SendPositionResponse createSendPositionResponse() {
        return new SendPositionResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendPositionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SendPositionRequest")
    public JAXBElement<SendPositionRequest> createSendPositionRequest(SendPositionRequest value) {
        return new JAXBElement<SendPositionRequest>(_SendPositionRequest_QNAME, SendPositionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendPositionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SendPositionResponse")
    public JAXBElement<SendPositionResponse> createSendPositionResponse(SendPositionResponse value) {
        return new JAXBElement<SendPositionResponse>(_SendPositionResponse_QNAME, SendPositionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link SendUserInfoDeptAllRequest }
     * 
     */
    public SendUserInfoDeptAllRequest createSendUserInfoDeptAllRequest() {
        return new SendUserInfoDeptAllRequest();
    }

    /**
     * Create an instance of {@link SendUserInfoDeptAllProcessReult }
     * 
     */
    public SendUserInfoDeptAllProcessReult createSendUserInfoDeptAllProcessReult() {
        return new SendUserInfoDeptAllProcessReult();
    }

    /**
     * Create an instance of {@link UserRoleDeptAllInfo }
     * 
     */
    public UserRoleDeptAllInfo createUserRoleDeptAllInfo() {
        return new UserRoleDeptAllInfo();
    }

    /**
     * Create an instance of {@link UserRoleDetailInfo }
     * 
     */
    public UserRoleDetailInfo createUserRoleDetailInfo() {
        return new UserRoleDetailInfo();
    }

    /**
     * Create an instance of {@link UserInfoDeptAll }
     * 
     */
    public UserInfoDeptAll createUserInfoDeptAll() {
        return new UserInfoDeptAll();
    }

    /**
     * Create an instance of {@link SendUserInfoDeptAllResponse }
     * 
     */
    public SendUserInfoDeptAllResponse createSendUserInfoDeptAllResponse() {
        return new SendUserInfoDeptAllResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendUserInfoDeptAllRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SendUserInfoDeptAllRequest")
    public JAXBElement<SendUserInfoDeptAllRequest> createSendUserInfoDeptAllRequest(SendUserInfoDeptAllRequest value) {
        return new JAXBElement<SendUserInfoDeptAllRequest>(_SendUserInfoDeptAllRequest_QNAME, SendUserInfoDeptAllRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendUserInfoDeptAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SendUserInfoDeptAllResponse")
    public JAXBElement<SendUserInfoDeptAllResponse> createSendUserInfoDeptAllResponse(SendUserInfoDeptAllResponse value) {
        return new JAXBElement<SendUserInfoDeptAllResponse>(_SendUserInfoDeptAllResponse_QNAME, SendUserInfoDeptAllResponse.class, null, value);
    }

}
