//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.03 at 11:51:09
//


package com.deppon.crm.module.interfaces.uums.jms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserRoleDeptAllInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserRoleDeptAllInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orgBenchmarkCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orgCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roleCode" type="{http://www.deppon.com/uums/inteface/domain/usermanagement}UserRoleDetailInfo" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserRoleDeptAllInfo", propOrder = {
    "orgBenchmarkCode",
    "orgCode",
    "roleCode"
})
public class UserRoleDeptAllInfo {

    @XmlElement(required = true)
    protected String orgBenchmarkCode;
    @XmlElement(required = true)
    protected String orgCode;
    @XmlElement(required = true)
    protected List<UserRoleDetailInfo> roleCode;

    /**
     * Gets the value of the orgBenchmarkCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgBenchmarkCode() {
        return orgBenchmarkCode;
    }

    /**
     * Sets the value of the orgBenchmarkCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgBenchmarkCode(String value) {
        this.orgBenchmarkCode = value;
    }

    /**
     * Gets the value of the orgCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * Sets the value of the orgCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgCode(String value) {
        this.orgCode = value;
    }

    /**
     * Gets the value of the roleCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserRoleDetailInfo }
     * 
     * 
     */
    public List<UserRoleDetailInfo> getRoleCode() {
        if (roleCode == null) {
            roleCode = new ArrayList<UserRoleDetailInfo>();
        }
        return this.roleCode;
    }

}
