//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.03 at 11:51:09
//


package com.deppon.crm.module.interfaces.uums.jms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserRoleDetailInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserRoleDetailInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roleCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roleBase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isDeptAll" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserRoleDetailInfo", propOrder = {
    "roleCode",
    "roleBase",
    "isDeptAll"
})
public class UserRoleDetailInfo {

    @XmlElement(required = true)
    protected String roleCode;
    @XmlElement(required = true)
    protected String roleBase;
    @XmlElement(required = true)
    protected String isDeptAll;

    /**
     * Gets the value of the roleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * Sets the value of the roleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleCode(String value) {
        this.roleCode = value;
    }

    /**
     * Gets the value of the roleBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleBase() {
        return roleBase;
    }

    /**
     * Sets the value of the roleBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleBase(String value) {
        this.roleBase = value;
    }

    /**
     * Gets the value of the isDeptAll property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDeptAll() {
        return isDeptAll;
    }

    /**
     * Sets the value of the isDeptAll property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDeptAll(String value) {
        this.isDeptAll = value;
    }

}
