CREATE TABLE T_CUST_INFORMUSER(
FID NUMBER,
FDUTYID NUMBER,
FUSERNAME VARCHAR2(60),
FUSERNO VARCHAR2(60),
FUSERPOSITION VARCHAR2(120),
FUSERCONTACT VARCHAR2(120),
FDEPTID NUMBER,
FUSERID NUMBER,
FVIRTUALCODING VARCHAR2(100),
FDEPTNAME VARCHAR2(100)
);
ALTER TABLE T_CUST_INFORMUSER ADD CONSTRAINT PK_T_CUST_INFORMUSER primary key (FID);
CREATE SEQUENCE SEQ_CRM_INFORMUSER start with 1 increment by 1;
COMMENT ON TABLE T_CUST_INFORMUSER is '通知对象';
COMMENT ON COLUMN T_CUST_INFORMUSER.FID is 'ID';
COMMENT ON COLUMN T_CUST_INFORMUSER.FDUTYID is '工单责任ID';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERNAME is '姓名';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERNO is '工号';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERPOSITION is '职位';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERCONTACT is '联系方式';
COMMENT ON COLUMN T_CUST_INFORMUSER.FDEPTID is '部门ID';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERID is '用户ID';
COMMENT ON COLUMN T_CUST_INFORMUSER.FVIRTUALCODING is '划分结果虚拟编码';
COMMENT ON COLUMN T_CUST_INFORMUSER.FDEPTNAME is '部门名称';
