CREATE TABLE T_CUST_HOLIDAY(
FID NUMBER,
FDATE TIMESTAMP,
FDATEFORMAT VARCHAR2(24),
FWEEKDAY VARCHAR2(24),
FSTATUS VARCHAR2(20)
);
ALTER TABLE T_CUST_HOLIDAY ADD CONSTRAINT PK_T_CUST_HOLIDAY primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_HOLIDAY start with 1 increment by 1;
COMMENT ON TABLE T_CUST_HOLIDAY is '节假日表';
COMMENT ON COLUMN T_CUST_HOLIDAY.FID is 'ID';
COMMENT ON COLUMN T_CUST_HOLIDAY.FDATE is '日期';
COMMENT ON COLUMN T_CUST_HOLIDAY.FDATEFORMAT is '日期格式';
COMMENT ON COLUMN T_CUST_HOLIDAY.FWEEKDAY is '星期';
COMMENT ON COLUMN T_CUST_HOLIDAY.FSTATUS is '工作日标识';
