CREATE TABLE T_CUST_DUBUSTYPE(
FID NUMBER,
FBUSSCOPEID NUMBER,
FBUSTYPENAME VARCHAR2(50),
FDEALLANGUAGE VARCHAR2(2000),
FREWORPUSTYPE VARCHAR2(20),
FFEEDDEADLINE NUMBER
);
ALTER TABLE T_CUST_DUBUSTYPE ADD CONSTRAINT PK_T_CUST_DUBUSTYPE primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUBUSTYPE start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUBUSTYPE is '业务类型表';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FID is '业务类型ID';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FBUSSCOPEID is '业务范围ID';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FBUSTYPENAME is '业务类型名称';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FDEALLANGUAGE is '处理语言';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FREWORPUSTYPE is '奖罚类型';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FFEEDDEADLINE is '反馈期限';
