CREATE TABLE T_CUST_DUBUSASPECT(
FID NUMBER,
FREPORTTYPE VARCHAR2(30),
FBUSASPNAME VARCHAR2(50)
);
ALTER TABLE T_CUST_DUBUSASPECT ADD CONSTRAINT PK_T_CUST_DUBUSASPECT primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUBUSASPECT start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUBUSASPECT is '业务环节表';
COMMENT ON COLUMN T_CUST_DUBUSASPECT.FID is 'ID';
COMMENT ON COLUMN T_CUST_DUBUSASPECT.FREPORTTYPE is '上报类型';
COMMENT ON COLUMN T_CUST_DUBUSASPECT.FBUSASPNAME is '业务环节名称';
