CREATE TABLE T_CUST_DUTYRESULT(
FID NUMBER,
FDUTYID NUMBER,
FDIVIDETYPE VARCHAR2(30),
FDUTYPERID NUMBER,
FDUTYPERNAME VARCHAR2(60),
FREWORPUSTYPE VARCHAR2(20),
FDUTYDEADLINE TIMESTAMP,
FBUSASPECT VARCHAR2(50),
FBUSSCOPE VARCHAR2(50),
FBUSTYPE VARCHAR2(50),
FDEALLANGUAGE VARCHAR2(1024),
FDUTYSTATUS VARCHAR2(30),
FSURVEYRESULT VARCHAR2(500),
FSTATUS VARCHAR2(20),
FMODIFYUSERID NUMBER,
FMODIFYTIME TIMESTAMP,
FBEFMODDETID NUMBER,
FBUSLINK VARCHAR2(50),
FVIRTUALCODING VARCHAR2(100),
FBUSASPECTID NUMBER,
FBUSSCOPEID NUMBER,
FBUSTYPEID NUMBER
);
ALTER TABLE T_CUST_DUTYRESULT ADD CONSTRAINT PK_T_CUST_DUTYRESULT primary key (FID);
CREATE SEQUENCE SEQ_CRM_DUTYRESULT start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUTYRESULT is '工单责任划分结果';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FID is '责任划分结果ID';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYID is '工单责任ID';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDIVIDETYPE is '划分类型';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYPERID is '责任人ID';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYPERNAME is '责任人名称';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FREWORPUSTYPE is '奖罚类型';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYDEADLINE is '反馈时限';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSASPECT is '业务项';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSSCOPE is '业务范围';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSTYPE is '业务类型';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDEALLANGUAGE is '处理语言';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYSTATUS is '责任状态';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FSURVEYRESULT is '调查结果';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FSTATUS is '工单详情状态';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FMODIFYUSERID is '修改人';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FMODIFYTIME is '修改时间';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBEFMODDETID is '修改前ID';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSLINK is '业务环节';
COMMENT ON COLUMN T_CUST_INFORMUSER.FVIRTUALCODING is '虚拟编码';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSASPECTID is '业务项ID';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSSCOPEID is '业务范围ID';
COMMENT ON COLUMN T_CUST_INFORMUSER.FBUSTYPEID is '业务类型ID';
