CREATE TABLE T_CUST_DUTYDEALPROCESS(
FID NUMBER,
FDUTYID NUMBER,
FTREATSTATUS VARCHAR2(30),
FTREATPROCESS VARCHAR2(500),
FOPERATORID NUMBER,
FOPERATORNAME VARCHAR2(60),
FOPERATORDATE TIMESTAMP
);
ALTER TABLE T_CUST_DUTYDEALPROCESS ADD CONSTRAINT PK_T_CUST_DUTYDEALPROCESS primary key (FID);
CREATE SEQUENCE SEQ_CRM_DUTYDEALPROCESS start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUTYDEALPROCESS is '处理进过表';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FID is 'ID';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FDUTYID is '责任ID';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FTREATSTATUS is '处理经过状态';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FTREATPROCESS is '处理经过';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FOPERATORID is '操作员ID';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FOPERATORNAME is '操作员姓名';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FOPERATORDATE is '操作时间';
