CREATE TABLE T_CUST_DUBUSSCOPE(
FID NUMBER,
FBUSASPECTID NUMBER,
FBUSCOPENAME VARCHAR2(50)
);
ALTER TABLE T_CUST_DUBUSSCOPE ADD CONSTRAINT PK_T_CUST_DUBUSSCOPE primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUBUSSCOPE start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUBUSSCOPE is '业务范围表';
COMMENT ON COLUMN T_CUST_DUBUSSCOPE.FID is 'ID';
COMMENT ON COLUMN T_CUST_DUBUSSCOPE.FBUSASPECTID is '业务环节ID';
COMMENT ON COLUMN T_CUST_DUBUSSCOPE.FBUSCOPENAME is '业务范围名称';
