CREATE TABLE T_CUST_DUTYFEEDBACK(
FID NUMBER,
FDETAILID NUMBER,
FFEEDUSERID NUMBER,
FFEEDUSERNAME VARCHAR2(60),
FFEEDDEPTID NUMBER,
FFEEDDEPTNAME VARCHAR2(128),
FDESCRIBE VARCHAR2(1024),
FFEEDBACKTIME TIMESTAMP,
FSTATUSERID NUMBER,
FSTATUSERNAME VARCHAR2(60),
FSTATDEPTID NUMBER,
FSTATDECISION VARCHAR2(1024),
FSTATTIME TIMESTAMP,
FCALLCENUSERID NUMBER,
FCALLCENUSER VARCHAR2(60),
FCALLCENDEPTID NUMBER,
FCALLCENDECISION VARCHAR2(1024),
FCALLCENTIME TIMESTAMP,
FSTATUS VARCHAR2(32),
FAPPSTATUS VARCHAR2(30),
FADDFEEDSTATUS VARCHAR2(20),
FACCORDING VARCHAR2(50)
);
ALTER TABLE T_CUST_DUTYFEEDBACK ADD CONSTRAINT PK_T_CUST_DUTYFEEDBACK primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUTYFEEDBACK start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUTYFEEDBACK is '工单责任反馈表';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FID is 'ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FDETAILID is '责任划分ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDUSERID is '反馈人ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDUSERNAME is '反馈人姓名';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDDEPTID is '反馈部门ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDDEPTNAME is '反馈部门名称';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FDESCRIBE is '反馈内容';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDBACKTIME is '反馈时间';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATUSERID is '统计员ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATUSERNAME  is '统计员姓名';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATDEPTID is '统计员所属部门ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATDECISION is '统计员审批意见';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENTIME is '呼叫中心审批时间';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENUSERID is '呼叫中心审批员ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENUSER is '呼叫中心审批员姓名';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENDEPTID is '呼叫中心部门ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENDECISION is '呼叫中心审批意见';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATTIME is '大区审批时间';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATUS is '工单责任状态';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FAPPSTATUS is '审批状态';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FADDFEEDSTATUS is '是否为补充反馈';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FACCORDING is '审批依据';



