ALTER TABLE T_CUST_DUBUSTYPE ADD CONSTRAINT FK_T_CUST_DUBUSTYPE_RE_DUBUSSCOPE FOREIGN KEY(FBUSSCOPEID) REFERENCES T_CUST_DUBUSSCOPE(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_DUBUSSCOPE ADD CONSTRAINT FK_T_CUST_DUBUSSCOPE_RE_DUBUSASPECT FOREIGN KEY(FBUSASPECTID) REFERENCES T_CUST_DUBUSASPECT(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_DUTYRESULT ADD CONSTRAINT FK_T_CUST_DUTYRESULT_RE_DUTY FOREIGN KEY(FDUTYID) REFERENCES T_CUST_DUTY(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_DUTYFEEDBACK ADD CONSTRAINT FK_T_CUST_DUFB_RE_DURST FOREIGN KEY(FDETAILID) REFERENCES T_CUST_DUTYRESULT(FID) ON DELETE CASCADE;
--ALTER TABLE T_CUST_FEEDATTACH ADD CONSTRAINT FK_T_CUST_FDATCH_RE_DUFB FOREIGN KEY(FFEEDID) REFERENCES T_CUST_DUTYRESULT(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_FEEDATTACH ADD CONSTRAINT FK_T_CUST_FDATCH_RE_DUFB FOREIGN KEY(FFEEDID) REFERENCES T_CUST_DUTYFEEDBACK(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_INFORMUSER ADD CONSTRAINT FK_T_CUST_INFUSER_RE_DUTY FOREIGN KEY(FDUTYID) REFERENCES T_CUST_DUTY(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_DUTYDEALPROCESS ADD CONSTRAINT FK_T_CUST_DDPRO_RE_DUTY FOREIGN KEY(FDUTYID) REFERENCES T_CUST_DUTY(FID) ON DELETE CASCADE;
