CREATE TABLE T_CUST_DUBUSASPECT(
FID NUMBER,
FREPORTTYPE VARCHAR2(30),
FBUSASPNAME VARCHAR2(50)
);
ALTER TABLE T_CUST_DUBUSASPECT ADD CONSTRAINT PK_T_CUST_DUBUSASPECT primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUBUSASPECT start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUBUSASPECT is '业务环节表';
COMMENT ON COLUMN T_CUST_DUBUSASPECT.FID is 'ID';
COMMENT ON COLUMN T_CUST_DUBUSASPECT.FREPORTTYPE is '上报类型';
COMMENT ON COLUMN T_CUST_DUBUSASPECT.FBUSASPNAME is '业务环节名称';


CREATE TABLE T_CUST_DUBUSSCOPE(
FID NUMBER,
FBUSASPECTID NUMBER,
FBUSCOPENAME VARCHAR2(50)
);
ALTER TABLE T_CUST_DUBUSSCOPE ADD CONSTRAINT PK_T_CUST_DUBUSSCOPE primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUBUSSCOPE start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUBUSSCOPE is '业务范围表';
COMMENT ON COLUMN T_CUST_DUBUSSCOPE.FID is 'ID';
COMMENT ON COLUMN T_CUST_DUBUSSCOPE.FBUSASPECTID is '业务环节ID';
COMMENT ON COLUMN T_CUST_DUBUSSCOPE.FBUSCOPENAME is '业务范围名称';


CREATE TABLE T_CUST_DUBUSTYPE(
FID NUMBER,
FBUSSCOPEID NUMBER,
FBUSTYPENAME VARCHAR2(50),
FDEALLANGUAGE VARCHAR2(2000),
FREWORPUSTYPE VARCHAR2(20),
FFEEDDEADLINE NUMBER
);
ALTER TABLE T_CUST_DUBUSTYPE ADD CONSTRAINT PK_T_CUST_DUBUSTYPE primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUBUSTYPE start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUBUSTYPE is '业务类型表';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FID is '业务类型ID';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FBUSSCOPEID is '业务范围ID';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FBUSTYPENAME is '业务类型名称';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FDEALLANGUAGE is '处理语言';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FREWORPUSTYPE is '奖罚类型';
COMMENT ON COLUMN T_CUST_DUBUSTYPE.FFEEDDEADLINE is '反馈期限';


CREATE TABLE T_CUST_DUTY(
FID NUMBER,
FCOMPLAINTID NUMBER,
FVOUCHERNUMBER VARCHAR2(300),
FCALLER VARCHAR2(60),
FDEALNUMBER VARCHAR2(50),
FTEL VARCHAR2(120),
FREPORTTYPE VARCHAR2(30),
FCOMPMANID NUMBER,
FCOMPLAINCUST VARCHAR2(500),
FSENDORRECEIVE VARCHAR2(20),
FCUSTLEVEL VARCHAR2(50),
FCUSTTYPE VARCHAR2(30),
FCOMPLAINTSOURCE VARCHAR2(50),
FRELATCUSID NUMBER,
FRELATCUS VARCHAR2(201),
FRELATCUSLEVEL VARCHAR2(30),
FRELATCUSTYPE VARCHAR2(50),
FTIMELIMIT NUMBER,
FTILIMITCYCLE VARCHAR2(30),
FPRIORITY VARCHAR2(30),
FREBINDNO VARCHAR2(60),
FREPORTERID NUMBER,
FREPORTER VARCHAR2(30),
FREPORTTIME TIMESTAMP,
FREPORTCONTENT VARCHAR2(4000),
FCUSTREQUIRE VARCHAR2(600),
FPROSTATUS VARCHAR2(50),
FSTATUS VARCHAR2(30),
FCREATETIME TIMESTAMP,
FCREATEUSERID NUMBER,
FRECEIVEUSERID NUMBER,
FRECEIVEUSER VARCHAR2(60),
FRECEIVETIME TIMESTAMP,
FAPPDUTYUSERID NUMBER,
FAPPDUTYUSER VARCHAR2(60),
FAPPDUTYTIME TIMESTAMP,
FSURVEYRESULT VARCHAR2(30)
);
ALTER TABLE T_CUST_DUTY ADD CONSTRAINT PK_T_CUST_DUTY primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUTY start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUTY is '工单责任';
COMMENT ON COLUMN T_CUST_DUTY.FID is '编号';
COMMENT ON COLUMN T_CUST_DUTY.FCOMPLAINTID is '工单编号';
COMMENT ON COLUMN T_CUST_DUTY.FVOUCHERNUMBER is '凭证号';
COMMENT ON COLUMN T_CUST_DUTY.FCALLER is '来电人';
COMMENT ON COLUMN T_CUST_DUTY.FDEALNUMBER is '处理编号';
COMMENT ON COLUMN T_CUST_DUTY.FTEL is '联系电话';
COMMENT ON COLUMN T_CUST_DUTY.FREPORTTYPE is '上报类型';
COMMENT ON COLUMN T_CUST_DUTY.FCOMPMANID is '来电客户ID';
COMMENT ON COLUMN T_CUST_DUTY.FCOMPLAINCUST is '来电客户';
COMMENT ON COLUMN T_CUST_DUTY.FSENDORRECEIVE is '来电人类型';
COMMENT ON COLUMN T_CUST_DUTY.FCUSTLEVEL is '客户等级';
COMMENT ON COLUMN T_CUST_DUTY.FCUSTTYPE is '客户类型';
COMMENT ON COLUMN T_CUST_DUTY.FCOMPLAINTSOURCE is '工单来源';
COMMENT ON COLUMN T_CUST_DUTY.FRELATCUSID is '相关客户ID';
COMMENT ON COLUMN T_CUST_DUTY.FRELATCUS is '相关客户';
COMMENT ON COLUMN T_CUST_DUTY.FRELATCUSLEVEL is '相关客户等级';
COMMENT ON COLUMN T_CUST_DUTY.FRELATCUSTYPE is '相关客户类型';
COMMENT ON COLUMN T_CUST_DUTY.FTIMELIMIT is '期望时限';
COMMENT ON COLUMN T_CUST_DUTY.FTILIMITCYCLE is '期望时限周期';
COMMENT ON COLUMN T_CUST_DUTY.FPRIORITY is '优先级别';
COMMENT ON COLUMN T_CUST_DUTY.FREBINDNO is '重复工单码';
COMMENT ON COLUMN T_CUST_DUTY.FREPORTERID is '上报人ID';
COMMENT ON COLUMN T_CUST_DUTY.FREPORTER is '上报人';
COMMENT ON COLUMN T_CUST_DUTY.FREPORTTIME is '上报时间';
COMMENT ON COLUMN T_CUST_DUTY.FREPORTCONTENT is '上报内容';
COMMENT ON COLUMN T_CUST_DUTY.FCUSTREQUIRE is '客户要求';
COMMENT ON COLUMN T_CUST_DUTY.FPROSTATUS is '处理状态';
COMMENT ON COLUMN T_CUST_DUTY.FSTATUS is '责任状态';
COMMENT ON COLUMN T_CUST_DUTY.FCREATETIME is '创建时间';
COMMENT ON COLUMN T_CUST_DUTY.FCREATEUSERID is '创建人编号';
COMMENT ON COLUMN T_CUST_DUTY.FRECEIVEUSERID is '接入人ID';
COMMENT ON COLUMN T_CUST_DUTY.FRECEIVEUSER is '接入人';
COMMENT ON COLUMN T_CUST_DUTY.FRECEIVETIME is '接入时间';
COMMENT ON COLUMN T_CUST_DUTY.FAPPDUTYUSERID is '责任划分人ID';
COMMENT ON COLUMN T_CUST_DUTY.FAPPDUTYUSER is '责任划分人';
COMMENT ON COLUMN T_CUST_DUTY.FAPPDUTYTIME is '责任划分时间';
COMMENT ON COLUMN T_CUST_DUTY.FSURVEYRESULT is '调查结果';


CREATE TABLE T_CUST_DUTYDEALPROCESS(
FID NUMBER,
FDUTYID NUMBER,
FTREATSTATUS VARCHAR2(30),
FTREATPROCESS VARCHAR2(500),
FOPERATORID NUMBER,
FOPERATORNAME VARCHAR2(60),
FOPERATORDATE TIMESTAMP
);
ALTER TABLE T_CUST_DUTYDEALPROCESS ADD CONSTRAINT PK_T_CUST_DUTYDEALPROCESS primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUTYDEALPROCESS start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUTYDEALPROCESS is '处理进过表';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FID is 'ID';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FDUTYID is '责任ID';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FTREATSTATUS is '处理经过状态';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FTREATPROCESS is '处理经过';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FOPERATORID is '操作员ID';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FOPERATORNAME is '操作员姓名';
COMMENT ON COLUMN T_CUST_DUTYDEALPROCESS.FOPERATORDATE is '操作时间';


CREATE TABLE T_CUST_DUTYFEEDBACK(
FID NUMBER,
FDETAILID NUMBER,
FFEEDUSERID NUMBER,
FFEEDUSERNAME VARCHAR2(60),
FFEEDDEPTID NUMBER,
FFEEDDEPTNAME VARCHAR2(128),
FDESCRIBE VARCHAR2(1024),
FSTATUSERID NUMBER,
FSTATUSERNAME VARCHAR2(60),
FSTATDEPTID NUMBER,
FSTATDECISION VARCHAR2(1024),
FCALLCENUSERID NUMBER,
FCALLCENUSER VARCHAR2(60),
FCALLCENDEPTID NUMBER,
FCALLCENDECISION VARCHAR2(1024),
FSTATUS VARCHAR2(32),
FAPPSTATUS VARCHAR2(30),
FADDFEEDSTATUS VARCHAR2(20),
FACCORDING VARCHAR2(50)
);
ALTER TABLE T_CUST_DUTYFEEDBACK ADD CONSTRAINT PK_T_CUST_DUTYFEEDBACK primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUTYFEEDBACK start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUTYFEEDBACK is '工单责任反馈表';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FID is 'ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FDETAILID is '责任划分ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDUSERID is '反馈人ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDUSERNAME is '反馈人姓名';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDDEPTID is '反馈部门ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FFEEDDEPTNAME is '反馈部门名称';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FDESCRIBE is '反馈内容';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATUSERID is '统计员ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATUSERNAME  is '统计员姓名';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATDEPTID is '统计员所属部门ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATDECISION is '统计员审批意见';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENUSERID is '呼叫中心审批员ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENUSER is '呼叫中心审批员姓名';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENDEPTID is '呼叫中心部门ID';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FCALLCENDECISION is '呼叫中心审批意见';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FSTATUS is '工单责任状态';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FAPPSTATUS is '审批状态';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FADDFEEDSTATUS is '是否为补充反馈';
COMMENT ON COLUMN T_CUST_DUTYFEEDBACK.FACCORDING is '审批依据';


CREATE TABLE T_CUST_DUTYRESULT(
FID NUMBER,
FDUTYID NUMBER,
FDIVIDETYPE VARCHAR2(30),
FDUTYPERID NUMBER,
FDUTYPERNAME VARCHAR2(60),
FREWORPUSTYPE VARCHAR2(20),
FDUTYDEADLINE TIMESTAMP,
FBUSASPECT VARCHAR2(50),
FBUSSCOPE VARCHAR2(50),
FBUSTYPE VARCHAR2(50),
FDEALLANGUAGE VARCHAR2(1024),
FDUTYSTATUS VARCHAR2(30),
FSURVEYRESULT VARCHAR2(500),
FSTATUS VARCHAR2(20),
FMODIFYUSERID NUMBER,
FMODIFYTIME TIMESTAMP,
FBEFMODDETID NUMBER
);
ALTER TABLE T_CUST_DUTYRESULT ADD CONSTRAINT PK_T_CUST_DUTYRESULT primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_DUTYRESULT start with 1 increment by 1;
COMMENT ON TABLE T_CUST_DUTYRESULT is '工单责任划分结果';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FID is '责任划分结果ID';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYID is '工单责任ID';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDIVIDETYPE is '划分类型';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYPERID is '责任人ID';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYPERNAME is '责任人名称';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FREWORPUSTYPE is '奖罚类型';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYDEADLINE is '反馈时限';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSASPECT is '业务环节';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSSCOPE is '业务范围';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBUSTYPE is '业务类型';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDEALLANGUAGE is '处理语言';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FDUTYSTATUS is '责任状态';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FSURVEYRESULT is '调查结果';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FSTATUS is '工单详情状态';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FMODIFYUSERID is '修改人';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FMODIFYTIME is '修改时间';
COMMENT ON COLUMN T_CUST_DUTYRESULT.FBEFMODDETID is '修改前ID';


CREATE TABLE T_CUST_FEEDATTACH(
FID NUMBER,
FFEEDID NUMBER,
FATTACHPATH VARCHAR2(500),
FATTACHNAME VARCHAR2(200),
FDESCRIBE VARCHAR2(1024)
);
ALTER TABLE T_CUST_FEEDATTACH ADD CONSTRAINT PK_T_CUST_FEEDATTACH primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_FEEDATTACH start with 1 increment by 1;
COMMENT ON TABLE T_CUST_FEEDATTACH is '反馈附件列表';
COMMENT ON COLUMN T_CUST_FEEDATTACH.FID is '附件ID';
COMMENT ON COLUMN T_CUST_FEEDATTACH.FFEEDID is '责任反馈ID';
COMMENT ON COLUMN T_CUST_FEEDATTACH.FATTACHPATH is '附件路径';
COMMENT ON COLUMN T_CUST_FEEDATTACH.FATTACHNAME is '附件名称';
COMMENT ON COLUMN T_CUST_FEEDATTACH.FDESCRIBE is '附件描述';


CREATE TABLE T_CUST_HOLIDAY(
FID NUMBER,
FDATE TIMESTAMP,
FDATEFORMAT VARCHAR2(24),
FWEEKDAY VARCHAR2(24),
FSTATUS VARCHAR2(20)
);
ALTER TABLE T_CUST_HOLIDAY ADD CONSTRAINT PK_T_CUST_HOLIDAY primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_HOLIDAY start with 1 increment by 1;
COMMENT ON TABLE T_CUST_HOLIDAY is '节假日表';
COMMENT ON COLUMN T_CUST_HOLIDAY.FID is 'ID';
COMMENT ON COLUMN T_CUST_HOLIDAY.FDATE is '日期';
COMMENT ON COLUMN T_CUST_HOLIDAY.FDATEFORMAT is '日期格式';
COMMENT ON COLUMN T_CUST_HOLIDAY.FWEEKDAY is '星期';
COMMENT ON COLUMN T_CUST_HOLIDAY.FSTATUS is '工作日标识';

CREATE TABLE T_CUST_INFORMUSER(
FID NUMBER,
FDUTYID NUMBER,
FUSERNAME VARCHAR2(60),
FUSERNO VARCHAR2(60),
FUSERPOSITION VARCHAR2(120),
FUSERCONTACT VARCHAR2(120),
FDEPTID NUMBER,
FUSERID NUMBER
);
ALTER TABLE T_CUST_INFORMUSER ADD CONSTRAINT PK_T_CUST_INFORMUSER primary key (FID);
CREATE SEQUENCE SEQ_ID_CUST_INFORMUSER start with 1 increment by 1;
COMMENT ON TABLE T_CUST_INFORMUSER is '通知对象';
COMMENT ON COLUMN T_CUST_INFORMUSER.FID is 'ID';
COMMENT ON COLUMN T_CUST_INFORMUSER.FDUTYID is '工单责任ID';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERNAME is '姓名';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERNO is '工号';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERPOSITION is '职位';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERCONTACT is '联系方式';
COMMENT ON COLUMN T_CUST_INFORMUSER.FDEPTID is '部门ID';
COMMENT ON COLUMN T_CUST_INFORMUSER.FUSERID is '用户ID';


ALTER TABLE T_CUST_DUBUSTYPE ADD CONSTRAINT FK_T_CUST_DUBUSTYPE_RE_DUBUSSCOPE FOREIGN KEY(FBUSSCOPEID) REFERENCES T_CUST_DUBUSSCOPE(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_DUBUSSCOPE ADD CONSTRAINT FK_T_CUST_DUBUSSCOPE_RE_DUBUSASPECT FOREIGN KEY(FBUSASPECTID) REFERENCES T_CUST_DUBUSASPECT(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_DUTYRESULT ADD CONSTRAINT FK_T_CUST_DUTYRESULT_RE_DUTY FOREIGN KEY(FDUTYID) REFERENCES T_CUST_DUTY(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_DUTYFEEDBACK ADD CONSTRAINT FK_T_CUST_DUFB_RE_DURST FOREIGN KEY(FDETAILID) REFERENCES T_CUST_DUTYRESULT(FID) ON DELETE CASCADE;
--ALTER TABLE T_CUST_FEEDATTACH ADD CONSTRAINT FK_T_CUST_FDATCH_RE_DUFB FOREIGN KEY(FFEEDID) REFERENCES T_CUST_DUTYRESULT(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_FEEDATTACH ADD CONSTRAINT FK_T_CUST_FDATCH_RE_DUFB FOREIGN KEY(FFEEDID) REFERENCES T_CUST_DUTYFEEDBACK(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_INFORMUSER ADD CONSTRAINT FK_T_CUST_INFUSER_RE_DUTY FOREIGN KEY(FDUTYID) REFERENCES T_CUST_DUTY(FID) ON DELETE CASCADE;
ALTER TABLE T_CUST_DUTYDEALPROCESS ADD CONSTRAINT FK_T_CUST_DDPRO_RE_DUTY FOREIGN KEY(FDUTYID) REFERENCES T_CUST_DUTY(FID) ON DELETE CASCADE;

