package com.deppon.oa.goodDelay;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-11-19T15:23:36.812+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "OAErrorForCRMImplServiceService", 
                  wsdlLocation = "http://192.168.14.88:8080/eos-default/OAErrorForCRMImplService?wsdl",
                  targetNamespace = "http://www.primeton.com/OAErrorForCRMImplService") 
public class OAErrorForCRMImplServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.primeton.com/OAErrorForCRMImplService", "OAErrorForCRMImplServiceService");
    public final static QName OAErrorForCRMImplServicePort = new QName("http://www.primeton.com/OAErrorForCRMImplService", "OAErrorForCRMImplServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.14.88:8080/eos-default/OAErrorForCRMImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OAErrorForCRMImplServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.14.88:8080/eos-default/OAErrorForCRMImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OAErrorForCRMImplServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OAErrorForCRMImplServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OAErrorForCRMImplServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OAErrorForCRMImplService
     */
    @WebEndpoint(name = "OAErrorForCRMImplServicePort")
    public OAErrorForCRMImplService getOAErrorForCRMImplServicePort() {
        return super.getPort(OAErrorForCRMImplServicePort, OAErrorForCRMImplService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OAErrorForCRMImplService
     */
    @WebEndpoint(name = "OAErrorForCRMImplServicePort")
    public OAErrorForCRMImplService getOAErrorForCRMImplServicePort(WebServiceFeature... features) {
        return super.getPort(OAErrorForCRMImplServicePort, OAErrorForCRMImplService.class, features);
    }

}
