package com.deppon.oa.goodDelay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-11-19T15:23:36.750+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.primeton.com/OAErrorForCRMImplService", name = "OAErrorForCRMImplService")
@XmlSeeAlso({ObjectFactory.class})
public interface OAErrorForCRMImplService {

    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/OAErrorForCRMImplService")
    @RequestWrapper(localName = "queryGoodDelay", targetNamespace = "http://www.primeton.com/OAErrorForCRMImplService", className = "com.deppon.oa.goodDelay.QueryGoodDelay")
    @WebMethod
    @ResponseWrapper(localName = "queryGoodDelayResponse", targetNamespace = "http://www.primeton.com/OAErrorForCRMImplService", className = "com.deppon.oa.goodDelay.QueryGoodDelayResponse")
    public java.lang.Boolean queryGoodDelay(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/OAErrorForCRMImplService")
        java.lang.String in0
    ) throws QueryGoodDelaySQLException, QueryGoodDelayException;
}
