package com.deppon.fin.selfservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * 生成报账报销单接口
 *
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-25T21:25:54.359+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "CrmService", 
                  wsdlLocation = "file:/D:/Java_Programs/workspace/CRM_QUERY_CLAIMBILL/FSSC_CRM_SERVICE.wsdl",
                  targetNamespace = "http://www.deppon.com/fssc/remote/crm") 
public class CrmService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.deppon.com/fssc/remote/crm", "CrmService");
    public final static QName CrmSOAP = new QName("http://www.deppon.com/fssc/remote/crm", "CrmSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Java_Programs/workspace/CRM_QUERY_CLAIMBILL/FSSC_CRM_SERVICE.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CrmService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Java_Programs/workspace/CRM_QUERY_CLAIMBILL/FSSC_CRM_SERVICE.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CrmService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CrmService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrmService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CrmService
     */
    @WebEndpoint(name = "CrmSOAP")
    public CrmService getCrmSOAP() {
        return super.getPort(CrmSOAP, CrmService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrmService
     */
    @WebEndpoint(name = "CrmSOAP")
    public CrmService getCrmSOAP(WebServiceFeature... features) {
        return super.getPort(CrmSOAP, CrmService.class, features);
    }

}
