-- 部门表-标杆编码
CREATE INDEX IDX_DEPT_FSTANDARDCODE ON T_ORG_DEPARTMENT (FSTANDARDCODE);
-- 部门表-SEQ
CREATE INDEX IDX_DEPT_FDEPTSEQ ON T_ORG_DEPARTMENT (FDEPTSEQ);

-- 手动券规则-营销计划（外键）
CREATE INDEX IDX_RULEHAND_FMARKETPLANID ON T_COU_RULECOUPONHAND (FMARKETPLANID);
-- 优惠券规则表-营销计划ID
CREATE INDEX IDX_COUPONRULE_FMARKETPLANID ON T_COU_COUPONRULE (FMARKETPLANID);


-- 优惠券表-营销计划（外键）
CREATE INDEX IDX_COUPON_FMARKETPLANID ON T_COU_COUPON (FMARKETPLANID);
-- 优惠券表-营销计划、优惠券状态
CREATE INDEX IDX_COUPON_PLANID_STATUS ON T_COU_COUPON (FMARKETPLANID,FSTATUS);
-- 优惠券表-发送时间
CREATE INDEX IDX_COUPON_SENDTIME ON T_COU_COUPON (FSENDTIME);
-- 优惠券表-使用时间
CREATE INDEX IDX_COUPON_USETIME ON T_COU_COUPON (FUSETIME);
-- 优惠券表-所属部门、规则ID
CREATE INDEX IDX_COUPON_SEARCH ON T_COU_COUPON (FMARKETPLANID, FUNDERDEPT);

       
