1 .--营销计划表
CREATE TABLE T_COU_MARKETPLAN(
     FID NUMBER(10,0),
     FSAVETIME TIMESTAMP(6),
     FCREATETIME TIMESTAMP(6),
     FCREATEUSERID NUMBER(10,0),
     FLASTUPDATTIME TIMESTAMP(6),
     FLASTMODIFYUSERID NUMBER(10,0),
     FPLANNUMBER VARCHAR2(25) NOT NULL,
     FPLANNAME VARCHAR2(300) NOT NULL,
     FSTATUS VARCHAR2(25),
     FCOUPONTYPE VARCHAR2(25),     
     CONSTRAINT PK_T_COU_MARKETPLAN PRIMARY KEY (FID)
);
1 .--营销计划序列
create sequence SEQ_ID_MARKETPLAN start with 1 increment by 1;
唯一键
alter table T_COU_MARKETPLAN add constraint UK_T_COU_MARKETPLAN unique (fplannumber);


2 .--手动发券规则表
CREATE TABLE T_COU_RULECOUPONHAND(
     FID NUMBER(10,0),
     FMARKETPLANID NUMBER(10,0) NOT NULL,
     FTYPEID VARCHAR2(20) NOT NULL,
     FVALUE VARCHAR2(20),
     FQUANTITY NUMBER(10,0),
     CONSTRAINT PK_T_COU_RULECOUPONHAND PRIMARY KEY (FID)
     );
2 .--手动发券规则表序列
create sequence SEQ_ID_RULECOUPONHAND start with 1 increment by 1;


3 .--自动发券规则表
CREATE TABLE T_COU_RULECOUPONAUTO(
     FID NUMBER(10,0),
     FBEGINTIME TIMESTAMP(6),
     FENDTIME TIMESTAMP(6),
     FMARKETPLANID NUMBER(10,0) NOT NULL,
     FTYPEID VARCHAR2(25) NOT NULL,
     CONSTRAINT PK_T_COU_RULECOUPONAUTO PRIMARY KEY (FID)
);
3 .--自动发券规则表序列
create sequence SEQ_ID_RULECOUPONAUTO start with 1 increment by 1;

4 .--自动发券-返券金额表
CREATE TABLE T_COU_AUTOCOUPONCOST(
     FID NUMBER(10,0),
     FCOUPONAUTOID NUMBER(10,0) NOT NULL,
     FCOSTTYPE VARCHAR2(20),
     FCOSTDOWN VARCHAR2(20),
     FCOUPONCOST VARCHAR2(20),
     CONSTRAINT PK_T_CUST_AUTOCOUPONCOST PRIMARY KEY (FID)
);
4 .--自动发券-返券金额表序列
create sequence SEQ_ID_AUTOCOUPONCOST start with 1 increment by 1;

5 .--优惠券使用规则表
CREATE TABLE T_COU_COUPONRULE(
     FID NUMBER(10,0),
     FBEGINTIME TIMESTAMP(6),
     FENDTIME TIMESTAMP(6),
     FMARKETPLANID NUMBER(10,0) NOT NULL,     
     FCOSTMODE VARCHAR2(20),
     FCOSTTYPE VARCHAR2(20),
     FVALUE VARCHAR2(20),
     FDISCOUNT VARCHAR2(20),
     FCOSTADDEDMODE VARCHAR2(20),
     FCOSTADDEDTYPE VARCHAR2(20),
     FCOSTADDED VARCHAR2(20),
     FSMS VARCHAR2(1000),
     FDESCRIBE VARCHAR2(2000),
     CONSTRAINT PK_T_COU_COUPONRULE PRIMARY KEY (FID)
);
5 .--优惠券使用规则表-序列
create sequence SEQ_ID_COUPONRULE start with 1 increment by 1;

6 .--优惠券表
CREATE TABLE T_COU_COUPON(
     FID NUMBER(10,0),
     FSMSTIMES NUMBER(10,0),
     FSENDTIME TIMESTAMP(6),
     FCREATETIME TIMESTAMP(6),
     FUSETIME TIMESTAMP(6),
     FNUMBER VARCHAR2(20) NOT NULL,
     FMARKETPLANID NUMBER(10,0) NOT NULL,
     FTYPEID VARCHAR2(20) NOT NULL,
     FCREATERULEID NUMBER(10,0),
     FUSERULEID NUMBER(10,0) NOT NULL,
     FSTATUS VARCHAR2(20) NOT NULL,
     FUNDERDEPT VARCHAR2(200),
     FSENDTELPHONE VARCHAR2(20),
     FUSETELPHONE VARCHAR2(20),
     FSOURCEWBNUMBER VARCHAR2(20),
     FSOURCEWBVALUE VARCHAR2(20),
     FUSEWBNUMBER VARCHAR2(20),
     FUSEWBVALUE VARCHAR2(20),   
     FVALUE VARCHAR2(20),   
     CONSTRAINT PK_T_COU_COUPON PRIMARY KEY (FID)
);
6 .--优惠券表序列
create sequence SEQ_ID_COUPON start with 1 increment by 1;
唯一键
alter table T_COU_COUPON add constraint UK_T_COU_COUPON unique (fnumber);


7 .--走货线路表
CREATE TABLE T_COU_GOODSLINE(
   FID  NUMBER(10,0),
   FRULETYPE VARCHAR2(20) NOT NULL,
   FCOUPONAUTOID  NUMBER(10,0),
   FCOUPONRULEID  NUMBER(10,0),
   FBEGINDEPTORCITYID  VARCHAR2(30),
   FBEGINDEPTORCITYNAME VARCHAR2(150),
   FENDDEPTORCITYID  VARCHAR2(30),
   FENDDEPTORCITYNAME VARCHAR2(150),
   FREGDEMAND  VARCHAR2(20),
   CONSTRAINT PK_T_COU_GOODSLINE PRIMARY KEY (FID)
);
7 .---走货线路表序列
create sequence SEQ_ID_GOODSLINE start with 1 increment by 1;

8 .--使用条件表
CREATE TABLE T_COU_CONDITIONTYPE(
   FID  NUMBER(10,0),
   FRULETYPE  VARCHAR2(20),
   FCOUPONAUTOID  NUMBER(10,0),
   FCOUPONRULEID  NUMBER(10,0),
   FTYPE  VARCHAR2(20),
   FVALUE  VARCHAR2(60),
   CONSTRAINT PK_T_COU_CONDITIONTYPE PRIMARY KEY (FID)
);
8 .--使用条件表序列
create sequence SEQ_ID_CONDITIONTYPE start with 1 increment by 1;

9. --优惠券短信发送表
create table T_COU_CELLPHONE_MSG_INFO(
       FID NUMBER primary key,
       FCOUNPON_NUMBER VARCHAR2(20) ,
       FPHONE_NUMBER VARCHAR2(30),
       FMSGCONTENT VARCHAR2(400),
       FSEND_STANDARD_DEPT_CODE VARCHAR2(30),
       FSENDER_EMP_CODE VARCHAR2(30),
       FIS_SENDED INTEGER,
       FCREATETIME TIMESTAMP
       );
9. --优惠券短信发送表-序列
   CREATE SEQUENCE SEQ_T_COU_PHONE_MSG_INFO
     INCREMENT BY 1   -- 每次加几个  
     START WITH 1     -- 从1开始计数  
     NOMAXVALUE       -- 不设置最大值  
     NOCYCLE          -- 一直累加，不循环  
     CACHE 10; 

10. --创建运单中间表
create table T_COU_WAYBILL_COUPON(
       FID NUMBER PRIMARY KEY,
       FWAYBILLNUMBER VARCHAR2(30),
       FMARKETPLANNUMBER  VARCHAR2(25),
       FUNDERDEPT  VARCHAR2(200),	
		 FSENDTELPHONE VARCHAR2(20),
		 FSOURCEWBVALUE VARCHAR2(20),
		 FVALUE VARCHAR2(20),
	    FSTATUS VARCHAR2(25),
		 FCREATETIME TIMESTAMP
);
10. --创建运单中间表-序列
   CREATE SEQUENCE SEQ_T_COU_WAYBILL_COUPON
     INCREMENT BY 1   -- 每次加几个  
     START WITH 1     -- 从1开始计数  
     NOMAXVALUE       -- 不设置最大值  
     NOCYCLE          -- 一直累加，不循环  
     CACHE 10; 















