-- 用于生成优惠券编码表
create table T_COU_COUPON_ORG_MESSAGE
(
  ORG_DATE    TIMESTAMP(6),
  ORG_NUMBER  VARCHAR2(12),
  ORG_CURRENT VARCHAR2(12)
);
INSERT INTO T_COU_COUPON_ORG_MESSAGE( ORG_DATE,ORG_NUMBER,ORG_CURRENT ) VALUES( SYSDATE,SUBSTR(PG_COU_COUPON.FN_DATE_TO_NUMBER(SYSDATE),-8,8),SUBSTR(PG_COU_COUPON.FN_DATE_TO_NUMBER(SYSDATE),-8,8));
COMMIT;
