package com.deppon.foss.framework.server.components.jobgrid.domain;

import java.io.Serializable;
import java.util.Date;

public class JobLogging implements Serializable {

    
    private String id;
   
    private String instanceId;
    
    private String triggerGroup;
   
    private String triggerName;
    
    private String jobGroup;
    
    private String jobName;
    
    private Date firedTime;
    
    private String jobAction;
   
    private String errorMessage;
    
    private String flowUuid;
    private static final long serialVersionUID = 1L;
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.ID
     * @param id  the value for quartz..job_logging.ID
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.CLUSTER_NAME
     * @return  the value of quartz..job_logging.CLUSTER_NAME
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.CLUSTER_NAME
     * @param instanceId  the value for quartz..job_logging.CLUSTER_NAME
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.TRIGGER_GROUP
     * @return  the value of quartz..job_logging.TRIGGER_GROUP
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.TRIGGER_GROUP
     * @param triggerGroup  the value for quartz..job_logging.TRIGGER_GROUP
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.TRIGGER_NAME
     * @return  the value of quartz..job_logging.TRIGGER_NAME
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.TRIGGER_NAME
     * @param triggerName  the value for quartz..job_logging.TRIGGER_NAME
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.JOB_GROUP
     * @return  the value of quartz..job_logging.JOB_GROUP
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.JOB_GROUP
     * @param jobGroup  the value for quartz..job_logging.JOB_GROUP
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.JOB_NAME
     * @return  the value of quartz..job_logging.JOB_NAME
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.JOB_NAME
     * @param jobName  the value for quartz..job_logging.JOB_NAME
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.FIRED_TIME
     * @return  the value of quartz..job_logging.FIRED_TIME
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public Date getFiredTime() {
        return firedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.FIRED_TIME
     * @param firedTime  the value for quartz..job_logging.FIRED_TIME
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setFiredTime(Date firedTime) {
        this.firedTime = firedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.JOB_ACTION
     * @return  the value of quartz..job_logging.JOB_ACTION
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public String getJobAction() {
        return jobAction;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.JOB_ACTION
     * @param jobAction  the value for quartz..job_logging.JOB_ACTION
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setJobAction(String jobAction) {
        this.jobAction = jobAction;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.ERROR_MESSAGE
     * @return  the value of quartz..job_logging.ERROR_MESSAGE
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.ERROR_MESSAGE
     * @param errorMessage  the value for quartz..job_logging.ERROR_MESSAGE
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column quartz..job_logging.FLOW_UUID
     * @return  the value of quartz..job_logging.FLOW_UUID
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public String getFlowUuid() {
        return flowUuid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column quartz..job_logging.FLOW_UUID
     * @param flowUuid  the value for quartz..job_logging.FLOW_UUID
     * @mbggenerated  Tue Oct 23 11:43:38 CST 2012
     */
    public void setFlowUuid(String flowUuid) {
        this.flowUuid = flowUuid;
    }
}