package com.deppon.esb.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-29T08:54:34.013+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://client.common.esb.deppon.com/", name = "ESBService")
@XmlSeeAlso({ObjectFactory.class})
public interface ESBService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "jsonProcess", targetNamespace = "http://client.common.esb.deppon.com/", className = "com.deppon.esb.ws.JsonProcess")
    @WebMethod
    @ResponseWrapper(localName = "jsonProcessResponse", targetNamespace = "http://client.common.esb.deppon.com/", className = "com.deppon.esb.ws.JsonProcessResponse")
    public java.lang.String jsonProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "process", targetNamespace = "http://client.common.esb.deppon.com/", className = "com.deppon.esb.ws.Process")
    @WebMethod
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://client.common.esb.deppon.com/", className = "com.deppon.esb.ws.ProcessResponse")
    public com.deppon.esb.ws.EsbJsonResponse process(
        @WebParam(name = "arg0", targetNamespace = "")
        com.deppon.esb.ws.EsbJsonRequest arg0
    ) throws Exception_Exception;
}
