package com.deppon.esb.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-29T08:54:34.013+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ESBServiceService", 
                  wsdlLocation = "http://192.168.17.142:8080/esb/webservice/workflow/apply?wsdl",
                  targetNamespace = "http://client.common.esb.deppon.com/") 
public class ESBServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://client.common.esb.deppon.com/", "ESBServiceService");
    public final static QName ESBServicePort = new QName("http://client.common.esb.deppon.com/", "ESBServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.17.142:8080/esb/webservice/workflow/apply?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ESBServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.17.142:8080/esb/webservice/workflow/apply?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ESBServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ESBServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ESBServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ESBService
     */
    @WebEndpoint(name = "ESBServicePort")
    public ESBService getESBServicePort() {
        return super.getPort(ESBServicePort, ESBService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ESBService
     */
    @WebEndpoint(name = "ESBServicePort")
    public ESBService getESBServicePort(WebServiceFeature... features) {
        return super.getPort(ESBServicePort, ESBService.class, features);
    }

}
