
package com.deppon.esb.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-29T08:54:33.998+08:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "Exception", targetNamespace = "http://client.common.esb.deppon.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.deppon.esb.ws.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.deppon.esb.ws.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.deppon.esb.ws.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.deppon.esb.ws.Exception getFaultInfo() {
        return this.exception;
    }
}
