
package com.deppon.foss.crm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-06-05T10:09:33.062+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class CustomerService_CustomerServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.deppon.com/foss/customerService", "CustomerService");

    private CustomerService_CustomerServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CustomerService_Service ss = new CustomerService_Service(wsdlURL, SERVICE_NAME);
        CustomerService port = ss.getCustomerServiceSOAP();  
        
        {
        System.out.println("Invoking claimsPayBillGenerate...");
        com.deppon.foss.crm.ESBHeader _claimsPayBillGenerate_esbHeaderVal = null;
        javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader> _claimsPayBillGenerate_esbHeader = new javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader>(_claimsPayBillGenerate_esbHeaderVal);
        com.deppon.foss.crm.ClaimsPayBillGenerateRequest _claimsPayBillGenerate_payload = null;
        try {
            com.deppon.foss.crm.ClaimsPayBillGenerateResponse _claimsPayBillGenerate__return = port.claimsPayBillGenerate(_claimsPayBillGenerate_esbHeader, _claimsPayBillGenerate_payload);
            System.out.println("claimsPayBillGenerate.result=" + _claimsPayBillGenerate__return);

            System.out.println("claimsPayBillGenerate._claimsPayBillGenerate_esbHeader=" + _claimsPayBillGenerate_esbHeader.value);
        } catch (CommonException e) { 
            System.out.println("Expected exception: CommonException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryMoney...");
        com.deppon.foss.crm.ESBHeader _queryMoney_esbHeaderVal = null;
        javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader> _queryMoney_esbHeader = new javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader>(_queryMoney_esbHeaderVal);
        com.deppon.foss.crm.QueryMoneyRequest _queryMoney_payload = null;
        try {
            com.deppon.foss.crm.QueryMoneyResponse _queryMoney__return = port.queryMoney(_queryMoney_esbHeader, _queryMoney_payload);
            System.out.println("queryMoney.result=" + _queryMoney__return);

            System.out.println("queryMoney._queryMoney_esbHeader=" + _queryMoney_esbHeader.value);
        } catch (CommonException e) { 
            System.out.println("Expected exception: CommonException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking qureyIsCustomeBlankOut...");
        com.deppon.foss.crm.IsCustomerBlankOutRequest _qureyIsCustomeBlankOut_request = null;
        com.deppon.foss.crm.ESBHeader _qureyIsCustomeBlankOut_esbHeaderVal = null;
        javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader> _qureyIsCustomeBlankOut_esbHeader = new javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader>(_qureyIsCustomeBlankOut_esbHeaderVal);
        try {
            com.deppon.foss.crm.IsCustomerBlankOutResponse _qureyIsCustomeBlankOut__return = port.qureyIsCustomeBlankOut(_qureyIsCustomeBlankOut_request, _qureyIsCustomeBlankOut_esbHeader);
            System.out.println("qureyIsCustomeBlankOut.result=" + _qureyIsCustomeBlankOut__return);

            System.out.println("qureyIsCustomeBlankOut._qureyIsCustomeBlankOut_esbHeader=" + _qureyIsCustomeBlankOut_esbHeader.value);
        } catch (CommonException e) { 
            System.out.println("Expected exception: CommonException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking bindOrder...");
        com.deppon.foss.crm.ESBHeader _bindOrder_esbHeaderVal = null;
        javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader> _bindOrder_esbHeader = new javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader>(_bindOrder_esbHeaderVal);
        com.deppon.foss.crm.BindOrderRequest _bindOrder_payload = null;
        try {
            com.deppon.foss.crm.BindOrderResponse _bindOrder__return = port.bindOrder(_bindOrder_esbHeader, _bindOrder_payload);
            System.out.println("bindOrder.result=" + _bindOrder__return);

            System.out.println("bindOrder._bindOrder_esbHeader=" + _bindOrder_esbHeader.value);
        } catch (CommonException e) { 
            System.out.println("Expected exception: CommonException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateServiceChargeStatus...");
        com.deppon.foss.crm.ESBHeader _updateServiceChargeStatus_esbHeaderVal = null;
        javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader> _updateServiceChargeStatus_esbHeader = new javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader>(_updateServiceChargeStatus_esbHeaderVal);
        com.deppon.foss.crm.ServiceChargeStatusUpdateRequest _updateServiceChargeStatus_payload = null;
        try {
            com.deppon.foss.crm.ServiceChargeStatusUpdateResponse _updateServiceChargeStatus__return = port.updateServiceChargeStatus(_updateServiceChargeStatus_esbHeader, _updateServiceChargeStatus_payload);
            System.out.println("updateServiceChargeStatus.result=" + _updateServiceChargeStatus__return);

            System.out.println("updateServiceChargeStatus._updateServiceChargeStatus_esbHeader=" + _updateServiceChargeStatus_esbHeader.value);
        } catch (CommonException e) { 
            System.out.println("Expected exception: CommonException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendGoodsBillReceive...");
        com.deppon.foss.crm.ESBHeader _sendGoodsBillReceive_esbHeaderVal = null;
        javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader> _sendGoodsBillReceive_esbHeader = new javax.xml.ws.Holder<com.deppon.foss.crm.ESBHeader>(_sendGoodsBillReceive_esbHeaderVal);
        com.deppon.foss.crm.GoodsBillReceiveRequest _sendGoodsBillReceive_payload = null;
        try {
            com.deppon.foss.crm.GoodsBillReceiveResponse _sendGoodsBillReceive__return = port.sendGoodsBillReceive(_sendGoodsBillReceive_esbHeader, _sendGoodsBillReceive_payload);
            System.out.println("sendGoodsBillReceive.result=" + _sendGoodsBillReceive__return);

            System.out.println("sendGoodsBillReceive._sendGoodsBillReceive_esbHeader=" + _sendGoodsBillReceive_esbHeader.value);
        } catch (CommonException e) { 
            System.out.println("Expected exception: CommonException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
