
package com.deppon.erp.custAndOrder;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-08-29T17:23:51.859+08:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "ERPBusinessFault", targetNamespace = "http://service.cms.ws.deppon.com/")
public class ERPBusinessException_Exception extends Exception {
    
    private com.deppon.erp.custAndOrder.ERPBusinessException erpBusinessFault;

    public ERPBusinessException_Exception() {
        super();
    }
    
    public ERPBusinessException_Exception(String message) {
        super(message);
    }
    
    public ERPBusinessException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ERPBusinessException_Exception(String message, com.deppon.erp.custAndOrder.ERPBusinessException erpBusinessFault) {
        super(message);
        this.erpBusinessFault = erpBusinessFault;
    }

    public ERPBusinessException_Exception(String message, com.deppon.erp.custAndOrder.ERPBusinessException erpBusinessFault, Throwable cause) {
        super(message, cause);
        this.erpBusinessFault = erpBusinessFault;
    }

    public com.deppon.erp.custAndOrder.ERPBusinessException getFaultInfo() {
        return this.erpBusinessFault;
    }
}
