package com.deppon.erp.custAndOrder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-08-29T17:23:51.890+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.cms.ws.deppon.com/", name = "IOrderAndCustService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IOrderAndCustService {

    @WebResult(name = "queryExceptionOrdersResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryExceptionOrdersResponse")
    @WebMethod
    public ExceptionOrderArray queryExceptionOrders(
        @WebParam(partName = "startTime", name = "startTime", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.util.Date startTime,
        @WebParam(partName = "endTime", name = "endTime", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.util.Date endTime
    ) throws ERPBusinessException_Exception;

    @WebResult(name = "queryExceptionCustResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryExceptionCustResponse")
    @WebMethod
    public ExceptionCustArray queryExceptionCust(
        @WebParam(partName = "queryExceptionCust", name = "queryExceptionCust", targetNamespace = "http://service.cms.ws.deppon.com/")
        StringArray queryExceptionCust
    ) throws ERPBusinessException_Exception;
}
