package com.deppon.oa.oaWorkflow;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-11-19T15:15:31.078+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.primeton.com/WorkFlowService", name = "WorkFlowService")
@XmlSeeAlso({ObjectFactory.class})
public interface WorkFlowService {

    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/WorkFlowService")
    @RequestWrapper(localName = "drawbackWorkFlow", targetNamespace = "http://www.primeton.com/WorkFlowService", className = "com.deppon.oa.oaWorkflow.DrawbackWorkFlow")
    @WebMethod
    @ResponseWrapper(localName = "drawbackWorkFlowResponse", targetNamespace = "http://www.primeton.com/WorkFlowService", className = "com.deppon.oa.oaWorkflow.DrawbackWorkFlowResponse")
    public java.lang.Boolean drawbackWorkFlow(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/WorkFlowService")
        java.lang.String in0
    ) throws DrawbackWorkFlowWorkFlowException;

    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/WorkFlowService")
    @RequestWrapper(localName = "deleteWorkFlow", targetNamespace = "http://www.primeton.com/WorkFlowService", className = "com.deppon.oa.oaWorkflow.DeleteWorkFlow")
    @WebMethod
    @ResponseWrapper(localName = "deleteWorkFlowResponse", targetNamespace = "http://www.primeton.com/WorkFlowService", className = "com.deppon.oa.oaWorkflow.DeleteWorkFlowResponse")
    public java.lang.Boolean deleteWorkFlow(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/WorkFlowService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://www.primeton.com/WorkFlowService")
        java.lang.String in1
    ) throws DeleteWorkFlowWorkFlowException;

    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/WorkFlowService")
    @RequestWrapper(localName = "createWorkFlow", targetNamespace = "http://www.primeton.com/WorkFlowService", className = "com.deppon.oa.oaWorkflow.CreateWorkFlow")
    @WebMethod
    @ResponseWrapper(localName = "createWorkFlowResponse", targetNamespace = "http://www.primeton.com/WorkFlowService", className = "com.deppon.oa.oaWorkflow.CreateWorkFlowResponse")
    public java.lang.String createWorkFlow(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/WorkFlowService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://www.primeton.com/WorkFlowService")
        java.lang.String in1
    ) throws CreateWorkFlowWorkFlowException;
}
