//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.02 at 02:56:41 下午 CST 
//


package com.deppon.crm.module.client.sync.wdgh;

import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CustDetalInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustDetalInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="regularCustName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transactionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deptName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deptCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custGenerateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="custCompanyAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cust_h_Coordinate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cust_v_Coordinate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custGrade" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="deliverGoodsMoney" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="isCustAvailable" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lastModifyTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustDetalInfo", propOrder = {
    "regularCustName",
    "custCode",
    "transactionCode",
    "deptName",
    "deptCode",
    "custGenerateTime",
    "custCompanyAddr",
    "custHCoordinate",
    "custVCoordinate",
    "custGrade",
    "deliverGoodsMoney",
    "isCustAvailable",
    "lastModifyTime"
})
public class CustDetalInfo {

    @XmlElement(required = true)
    protected String regularCustName;
    @XmlElement(required = true)
    protected String custCode;
    @XmlElement(required = true)
    protected String transactionCode;
    @XmlElement(required = true)
    protected String deptName;
    @XmlElement(required = true)
    protected String deptCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date custGenerateTime;
    @XmlElement(required = true)
    protected String custCompanyAddr;
    @XmlElement(name = "cust_h_Coordinate")
    protected String custHCoordinate;
    @XmlElement(name = "cust_v_Coordinate")
    protected String custVCoordinate;
    protected String custGrade;
    @XmlElement(required = true)
    protected BigDecimal deliverGoodsMoney;
    protected int isCustAvailable;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date lastModifyTime;

    /**
     * Gets the value of the regularCustName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegularCustName() {
        return regularCustName;
    }

    /**
     * Sets the value of the regularCustName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegularCustName(String value) {
        this.regularCustName = value;
    }

    /**
     * Gets the value of the custCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * Sets the value of the custCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustCode(String value) {
        this.custCode = value;
    }

    /**
     * Gets the value of the transactionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionCode() {
        return transactionCode;
    }

    /**
     * Sets the value of the transactionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionCode(String value) {
        this.transactionCode = value;
    }

    /**
     * Gets the value of the deptName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * Sets the value of the deptName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeptName(String value) {
        this.deptName = value;
    }

    /**
     * Gets the value of the deptCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * Sets the value of the deptCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeptCode(String value) {
        this.deptCode = value;
    }

    /**
     * Gets the value of the custGenerateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getCustGenerateTime() {
        return custGenerateTime;
    }

    /**
     * Sets the value of the custGenerateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCustGenerateTime(Date value) {
        this.custGenerateTime = value;
    }

    /**
     * Gets the value of the custCompanyAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustCompanyAddr() {
        return custCompanyAddr;
    }

    /**
     * Sets the value of the custCompanyAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustCompanyAddr(String value) {
        this.custCompanyAddr = value;
    }

    /**
     * Gets the value of the custHCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustHCoordinate() {
        return custHCoordinate;
    }

    /**
     * Sets the value of the custHCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustHCoordinate(String value) {
        this.custHCoordinate = value;
    }

    /**
     * Gets the value of the custVCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustVCoordinate() {
        return custVCoordinate;
    }

    /**
     * Sets the value of the custVCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustVCoordinate(String value) {
        this.custVCoordinate = value;
    }

    /**
     * Gets the value of the custGrade property.
     * 
     */
    public String getCustGrade() {
        return custGrade;
    }

    /**
     * Sets the value of the custGrade property.
     * 
     */
    public void setCustGrade(String value) {
        this.custGrade = value;
    }

    /**
     * Gets the value of the deliverGoodsMoney property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeliverGoodsMoney() {
        return deliverGoodsMoney;
    }

    /**
     * Sets the value of the deliverGoodsMoney property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeliverGoodsMoney(BigDecimal value) {
        this.deliverGoodsMoney = value;
    }

    /**
     * Gets the value of the isCustAvailable property.
     * 
     */
    public int getIsCustAvailable() {
        return isCustAvailable;
    }

    /**
     * Sets the value of the isCustAvailable property.
     * 
     */
    public void setIsCustAvailable(int value) {
        this.isCustAvailable = value;
    }

    /**
     * Gets the value of the lastModifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * Sets the value of the lastModifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifyTime(Date value) {
        this.lastModifyTime = value;
    }

	@Override
	public String toString() {
		return "CustDetalInfo [regularCustName=" + regularCustName
				+ ",\n custCode=" + custCode + ",\n transactionCode="
				+ transactionCode + ",\n deptName=" + deptName + ",\n deptCode="
				+ deptCode + ",\n custGenerateTime=" + custGenerateTime
				+ ",\n custCompanyAddr=" + custCompanyAddr + ",\n custHCoordinate="
				+ custHCoordinate + ",\n custVCoordinate=" + custVCoordinate
				+ ",\n custGrade=" + custGrade + ",\n deliverGoodsMoney="
				+ deliverGoodsMoney + ",\n isCustAvailable=" + isCustAvailable
				+ ",\n lastModifyTime=" + lastModifyTime + "]";
	}

    
}
