//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.02 at 02:56:41 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deppon.com/esb/inteface/domain/crm", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.deppon.crm.module.client.sync.wdgh;
