//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 08:37:14 上午 CST 
//


package com.deppon.crm.module.client.esb.domain;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 价格折扣信息
 * 
 * <p>Java class for DiscountInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscountInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fid" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="preferentialProduct" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceDiscount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscountInfo", propOrder = {
    "fid",
    "preferentialProduct",
    "priceDiscount"
})
public class DiscountInfo {

    @XmlElement(required = true)
    protected BigDecimal fid;
    @XmlElement(required = true)
    protected String preferentialProduct;
    @XmlElement(required = true)
    protected String priceDiscount;

    /**
     * Gets the value of the fid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFid() {
        return fid;
    }

    /**
     * Sets the value of the fid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFid(BigDecimal value) {
        this.fid = value;
    }

    /**
     * Gets the value of the preferentialProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferentialProduct() {
        return preferentialProduct;
    }

    /**
     * Sets the value of the preferentialProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferentialProduct(String value) {
        this.preferentialProduct = value;
    }

    /**
     * Gets the value of the priceDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceDiscount() {
        return priceDiscount;
    }

    /**
     * Sets the value of the priceDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceDiscount(String value) {
        this.priceDiscount = value;
    }

}
