//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.28 at 10:05:23 上午 CST
//


package com.deppon.crm.module.client.esb.domain;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketingActivityResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MarketingActivityResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="errorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketingActivityResponse", propOrder = {
	"fid",
    "result",
    "errorMsg"
})
public class MarketingActivityResponse {
	@XmlElement(required = true)
    protected BigDecimal fid;
    protected boolean result;
    @XmlElement(required = true)
    protected String errorMsg;

    /**
     * Gets the value of the result property.
     *
     */
    public boolean isResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     *
     */
    public void setResult(boolean value) {
        this.result = value;
    }

    /**
     * Gets the value of the errorMsg property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * Sets the value of the errorMsg property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setErrorMsg(String value) {
        this.errorMsg = value;
    }

	/**
	 * @return fid : return the property fid.
	 */
	public BigDecimal getFid() {
		return fid;
	}

	/**
	 * @param fid : set the property fid.
	 */
	public void setFid(BigDecimal fid) {
		this.fid = fid;
	}
}
