//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.09 at 08:37:14 上午 CST
//


package com.deppon.crm.module.client.esb.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 市场推广活动信息
 *
 * <p>Java class for MarketingActivityRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MarketingActivityRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fid" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="activityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activityCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="discountInfos" type="{http://www.deppon.com/esb/inteface/domain/crm}DiscountInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="activityBeginTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="activityEndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="firstTrades" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="secondTrades" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="activityCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="goodsName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="billMinMoney" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billMaxMoney" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="goodsMinWeight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="goodsMaxWeight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="goodsMinVolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="goodsMaxVolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderResource" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="developDeptInfos" type="{http://www.deppon.com/esb/inteface/domain/crm}DevelopDeptInfos" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="goodsLine" type="{http://www.deppon.com/esb/inteface/domain/crm}GoodsLine" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketingActivityRequest", propOrder = {
    "fid",
    "activityName",
    "activityCode",
    "discountInfos",
    "activityBeginTime",
    "activityEndTime",
    "firstTrades",
    "secondTrades",
    "activityCategory",
    "activityType",
    "productType",
    "goodsName",
    "billMinMoney",
    "billMaxMoney",
    "goodsMinWeight",
    "goodsMaxWeight",
    "goodsMinVolume",
    "goodsMaxVolume",
    "orderResource",
    "developDeptInfos",
    "goodsLine",
    "fstatus"
})
public class MarketingActivityRequest {

    @XmlElement(required = true)
    protected BigDecimal fid;
    @XmlElement(required = true)
    protected String activityName;
    @XmlElement(required = true)
    protected String activityCode;
    protected List<DiscountInfo> discountInfos;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date activityBeginTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date activityEndTime;
    protected List<String> firstTrades;
    protected List<String> secondTrades;
    @XmlElement(required = true)
    protected String activityCategory;
    @XmlElement(required = true)
    protected String activityType;
    protected List<String> productType;
    protected List<String> goodsName;
    @XmlElement(required = true)
    protected String billMinMoney;
    @XmlElement(required = true)
    protected String billMaxMoney;
    @XmlElement(required = true)
    protected String goodsMinWeight;
    @XmlElement(required = true)
    protected String goodsMaxWeight;
    @XmlElement(required = true)
    protected String goodsMinVolume;
    @XmlElement(required = true)
    protected String goodsMaxVolume;
    protected List<String> orderResource;
    protected List<DevelopDeptInfos> developDeptInfos;
    protected List<GoodsLine> goodsLine;
    protected String fstatus;

    /**
     * Gets the value of the fid property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getFid() {
        return fid;
    }

    /**
     * Sets the value of the fid property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setFid(BigDecimal value) {
        this.fid = value;
    }

    /**
     * Gets the value of the activityName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * Sets the value of the activityName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActivityName(String value) {
        this.activityName = value;
    }

    /**
     * Gets the value of the activityCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * Sets the value of the activityCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActivityCode(String value) {
        this.activityCode = value;
    }

    /**
     * Gets the value of the discountInfos property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discountInfos property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscountInfos().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiscountInfo }
     *
     *
     */
    public List<DiscountInfo> getDiscountInfos() {
        if (discountInfos == null) {
            discountInfos = new ArrayList<DiscountInfo>();
        }
        return this.discountInfos;
    }

    /**
     * Gets the value of the activityBeginTime property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public Date getActivityBeginTime() {
        return activityBeginTime;
    }

    /**
     * Sets the value of the activityBeginTime property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setActivityBeginTime(Date value) {
        this.activityBeginTime = value;
    }

    /**
     * Gets the value of the activityEndTime property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public Date getActivityEndTime() {
        return activityEndTime;
    }

    /**
     * Sets the value of the activityEndTime property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setActivityEndTime(Date value) {
        this.activityEndTime = value;
    }

    /**
     * Gets the value of the firstTrades property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the firstTrades property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFirstTrades().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getFirstTrades() {
        if (firstTrades == null) {
            firstTrades = new ArrayList<String>();
        }
        return this.firstTrades;
    }

    /**
     * Gets the value of the secondTrades property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secondTrades property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecondTrades().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getSecondTrades() {
        if (secondTrades == null) {
            secondTrades = new ArrayList<String>();
        }
        return this.secondTrades;
    }

    /**
     * Gets the value of the activityCategory property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getActivityCategory() {
        return activityCategory;
    }

    /**
     * Sets the value of the activityCategory property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActivityCategory(String value) {
        this.activityCategory = value;
    }

    /**
     * Gets the value of the activityType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * Sets the value of the activityType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActivityType(String value) {
        this.activityType = value;
    }

    /**
     * Gets the value of the productType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getProductType() {
        if (productType == null) {
            productType = new ArrayList<String>();
        }
        return this.productType;
    }

    /**
     * Gets the value of the goodsName property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goodsName property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoodsName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getGoodsName() {
        if (goodsName == null) {
            goodsName = new ArrayList<String>();
        }
        return this.goodsName;
    }

    /**
     * Gets the value of the billMinMoney property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBillMinMoney() {
        return billMinMoney;
    }

    /**
     * Sets the value of the billMinMoney property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBillMinMoney(String value) {
        this.billMinMoney = value;
    }

    /**
     * Gets the value of the billMaxMoney property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBillMaxMoney() {
        return billMaxMoney;
    }

    /**
     * Sets the value of the billMaxMoney property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBillMaxMoney(String value) {
        this.billMaxMoney = value;
    }

    /**
     * Gets the value of the goodsMinWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGoodsMinWeight() {
        return goodsMinWeight;
    }

    /**
     * Sets the value of the goodsMinWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGoodsMinWeight(String value) {
        this.goodsMinWeight = value;
    }

    /**
     * Gets the value of the goodsMaxWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGoodsMaxWeight() {
        return goodsMaxWeight;
    }

    /**
     * Sets the value of the goodsMaxWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGoodsMaxWeight(String value) {
        this.goodsMaxWeight = value;
    }

    /**
     * Gets the value of the goodsMinVolume property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGoodsMinVolume() {
        return goodsMinVolume;
    }

    /**
     * Sets the value of the goodsMinVolume property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGoodsMinVolume(String value) {
        this.goodsMinVolume = value;
    }

    /**
     * Gets the value of the goodsMaxVolume property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGoodsMaxVolume() {
        return goodsMaxVolume;
    }

    /**
     * Sets the value of the goodsMaxVolume property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGoodsMaxVolume(String value) {
        this.goodsMaxVolume = value;
    }

    /**
     * Gets the value of the orderResource property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderResource property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderResource().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getOrderResource() {
        if (orderResource == null) {
            orderResource = new ArrayList<String>();
        }
        return this.orderResource;
    }

    /**
     * Gets the value of the developDeptInfos property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the developDeptInfos property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDevelopDeptInfos().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DevelopDeptInfos }
     *
     *
     */
    public List<DevelopDeptInfos> getDevelopDeptInfos() {
        if (developDeptInfos == null) {
            developDeptInfos = new ArrayList<DevelopDeptInfos>();
        }
        return this.developDeptInfos;
    }

    /**
     * Gets the value of the goodsLine property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goodsLine property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoodsLine().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GoodsLine }
     *
     *
     */
    public List<GoodsLine> getGoodsLine() {
        if (goodsLine == null) {
            goodsLine = new ArrayList<GoodsLine>();
        }
        return this.goodsLine;
    }

	public String getFstatus() {
		return fstatus;
	}

	public void setFstatus(String fstatus) {
		this.fstatus = fstatus;
	}

}
