package com.deppon.fin.badDebt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-01-11T16:32:12.860+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://server.foss.webservice.server.baddebt.module.fin.deppon.com/", name = "IBadDebtInterService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IBadDebtInterService {

    @WebResult(name = "return", targetNamespace = "http://server.foss.webservice.server.baddebt.module.fin.deppon.com/", partName = "return")
    @WebMethod
    public boolean checkBadDebt(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;
}
