package com.deppon.fin.badDebt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-01-11T16:32:12.875+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "IBadDebtInterServiceService", 
                  wsdlLocation = "http://192.168.20.50:8080/financManager/webservice/badBebtInterService?wsdl",
                  targetNamespace = "http://server.foss.webservice.server.baddebt.module.fin.deppon.com/") 
public class IBadDebtInterServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.foss.webservice.server.baddebt.module.fin.deppon.com/", "IBadDebtInterServiceService");
    public final static QName IBadDebtInterServicePort = new QName("http://server.foss.webservice.server.baddebt.module.fin.deppon.com/", "IBadDebtInterServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.20.50:8080/financManager/webservice/badBebtInterService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IBadDebtInterServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.20.50:8080/financManager/webservice/badBebtInterService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IBadDebtInterServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IBadDebtInterServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IBadDebtInterServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IBadDebtInterService
     */
    @WebEndpoint(name = "IBadDebtInterServicePort")
    public IBadDebtInterService getIBadDebtInterServicePort() {
        return super.getPort(IBadDebtInterServicePort, IBadDebtInterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBadDebtInterService
     */
    @WebEndpoint(name = "IBadDebtInterServicePort")
    public IBadDebtInterService getIBadDebtInterServicePort(WebServiceFeature... features) {
        return super.getPort(IBadDebtInterServicePort, IBadDebtInterService.class, features);
    }

}
