package com.deppon.bi.arrived;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-08T15:22:57.569+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.example.org/CRM_CusArrStaByNum/", name = "CRM_CusArrStaByNum")
@XmlSeeAlso({ObjectFactory.class})
public interface CRMCusArrStaByNum {

    @WebResult(name = "out1", targetNamespace = "")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.example.org/CRM_CusArrStaByNum/", className = "com.deppon.bi.arrived.NewOperation")
    @WebMethod(operationName = "NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.example.org/CRM_CusArrStaByNum/", className = "com.deppon.bi.arrived.NewOperationResponse")
    public java.lang.String newOperation(
        @WebParam(name = "in0", targetNamespace = "")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "")
        java.util.Date in1
    );
}
