package com.deppon.bi.arrived;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-08T15:22:57.585+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "CRM_CusArrStaByNumService", 
                  wsdlLocation = "http://192.168.14.19:8080/eos-default/CRM_CusArrStaByNumService?wsdl",
                  targetNamespace = "http://www.example.org/CRM_CusArrStaByNumService") 
public class CRMCusArrStaByNumService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/CRM_CusArrStaByNumService", "CRM_CusArrStaByNumService");
    public final static QName CRMCusArrStaByNumPort = new QName("http://www.example.org/CRM_CusArrStaByNumService", "CRM_CusArrStaByNumPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.14.19:8080/eos-default/CRM_CusArrStaByNumService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CRMCusArrStaByNumService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.14.19:8080/eos-default/CRM_CusArrStaByNumService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CRMCusArrStaByNumService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CRMCusArrStaByNumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRMCusArrStaByNumService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CRMCusArrStaByNum
     */
    @WebEndpoint(name = "CRM_CusArrStaByNumPort")
    public CRMCusArrStaByNum getCRMCusArrStaByNumPort() {
        return super.getPort(CRMCusArrStaByNumPort, CRMCusArrStaByNum.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMCusArrStaByNum
     */
    @WebEndpoint(name = "CRM_CusArrStaByNumPort")
    public CRMCusArrStaByNum getCRMCusArrStaByNumPort(WebServiceFeature... features) {
        return super.getPort(CRMCusArrStaByNumPort, CRMCusArrStaByNum.class, features);
    }

}
