//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 09:55:50 上午 CST 
//


package com.deppon.crm.module.interfaces.ows.jmsdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateOwsCustomerResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateOwsCustomerResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ifSuccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="linkmanId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateOwsCustomerResponse", propOrder = {
    "ifSuccess",
    "userName",
    "linkmanId"
})
public class CreateOwsCustomerResponse {

    protected boolean ifSuccess;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String linkmanId;

    /**
     * Gets the value of the ifSuccess property.
     * 
     */
    public boolean isIfSuccess() {
        return ifSuccess;
    }

    /**
     * Sets the value of the ifSuccess property.
     * 
     */
    public void setIfSuccess(boolean value) {
        this.ifSuccess = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the linkmanId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkmanId() {
        return linkmanId;
    }

    /**
     * Sets the value of the linkmanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkmanId(String value) {
        this.linkmanId = value;
    }

}
