//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 09:55:50 上午 CST 
//


package com.deppon.crm.module.interfaces.ows.jmsdomain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.deppon.crm.remote.ows.domain.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateOwsCustomerResponse_QNAME = new QName("http://www.deppon.com/crm/remote/ows/domain/entity", "createOwsCustomerResponse");
    private final static QName _CreateOwsCustomerRequest_QNAME = new QName("http://www.deppon.com/crm/remote/ows/domain/entity", "createOwsCustomerRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deppon.crm.remote.ows.domain.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateOwsCustomerResponse }
     * 
     */
    public CreateOwsCustomerResponse createCreateOwsCustomerResponse() {
        return new CreateOwsCustomerResponse();
    }

    /**
     * Create an instance of {@link CreateOwsCustomerRequest }
     * 
     */
    public CreateOwsCustomerRequest createCreateOwsCustomerRequest() {
        return new CreateOwsCustomerRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOwsCustomerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/crm/remote/ows/domain/entity", name = "createOwsCustomerResponse")
    public JAXBElement<CreateOwsCustomerResponse> createCreateOwsCustomerResponse(CreateOwsCustomerResponse value) {
        return new JAXBElement<CreateOwsCustomerResponse>(_CreateOwsCustomerResponse_QNAME, CreateOwsCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOwsCustomerRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/crm/remote/ows/domain/entity", name = "createOwsCustomerRequest")
    public JAXBElement<CreateOwsCustomerRequest> createCreateOwsCustomerRequest(CreateOwsCustomerRequest value) {
        return new JAXBElement<CreateOwsCustomerRequest>(_CreateOwsCustomerRequest_QNAME, CreateOwsCustomerRequest.class, null, value);
    }

}
