
package com.deppon.crm.module.interfaces.order;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-06-26T14:34:01.953+08:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "CrmBusiness", targetNamespace = "http://exception.common.client.module.crm.deppon.com")
public class CrmBusinessException extends Exception {
    
    private com.deppon.crm.module.client.common.exception.CrmBusiness crmBusiness;

    public CrmBusinessException() {
        super();
    }
    
    public CrmBusinessException(String message) {
        super(message);
    }
    
    public CrmBusinessException(String message, Throwable cause) {
        super(message, cause);
    }

    public CrmBusinessException(String message, com.deppon.crm.module.client.common.exception.CrmBusiness crmBusiness) {
        super(message);
        this.crmBusiness = crmBusiness;
    }

    public CrmBusinessException(String message, com.deppon.crm.module.client.common.exception.CrmBusiness crmBusiness, Throwable cause) {
        super(message, cause);
        this.crmBusiness = crmBusiness;
    }

    public com.deppon.crm.module.client.common.exception.CrmBusiness getFaultInfo() {
        return this.crmBusiness;
    }
}
