package com.deppon.ebm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-07T21:09:50.618+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.shared.aliOrder.module.alibaba.deppon.com/", name = "IUpdateOrderStatusWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IUpdateOrderStatusWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "process", targetNamespace = "http://ws.shared.aliOrder.module.alibaba.deppon.com/", className = "com.deppon.ebm.Process")
    @WebMethod
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://ws.shared.aliOrder.module.alibaba.deppon.com/", className = "com.deppon.ebm.ProcessResponse")
    public com.deppon.ebm.EbmResponse process(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
