package com.deppon.crm.module.client.sync.dao.impl;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCustPreferentialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public TCustPreferentialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFidIsNull() {
            addCriterion("FID is null");
            return (Criteria) this;
        }

        public Criteria andFidIsNotNull() {
            addCriterion("FID is not null");
            return (Criteria) this;
        }

        public Criteria andFidEqualTo(Short value) {
            addCriterion("FID =", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotEqualTo(Short value) {
            addCriterion("FID <>", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThan(Short value) {
            addCriterion("FID >", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThanOrEqualTo(Short value) {
            addCriterion("FID >=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThan(Short value) {
            addCriterion("FID <", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThanOrEqualTo(Short value) {
            addCriterion("FID <=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidIn(List<Short> values) {
            addCriterion("FID in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotIn(List<Short> values) {
            addCriterion("FID not in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidBetween(Short value1, Short value2) {
            addCriterion("FID between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotBetween(Short value1, Short value2) {
            addCriterion("FID not between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNull() {
            addCriterion("FCREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNotNull() {
            addCriterion("FCREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeEqualTo(Date value) {
            addCriterion("FCREATETIME =", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotEqualTo(Date value) {
            addCriterion("FCREATETIME <>", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThan(Date value) {
            addCriterion("FCREATETIME >", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FCREATETIME >=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThan(Date value) {
            addCriterion("FCREATETIME <", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("FCREATETIME <=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIn(List<Date> values) {
            addCriterion("FCREATETIME in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotIn(List<Date> values) {
            addCriterion("FCREATETIME not in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeBetween(Date value1, Date value2) {
            addCriterion("FCREATETIME between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("FCREATETIME not between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNull() {
            addCriterion("FCREATEUSERID is null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNotNull() {
            addCriterion("FCREATEUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridEqualTo(Short value) {
            addCriterion("FCREATEUSERID =", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotEqualTo(Short value) {
            addCriterion("FCREATEUSERID <>", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThan(Short value) {
            addCriterion("FCREATEUSERID >", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThanOrEqualTo(Short value) {
            addCriterion("FCREATEUSERID >=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThan(Short value) {
            addCriterion("FCREATEUSERID <", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThanOrEqualTo(Short value) {
            addCriterion("FCREATEUSERID <=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIn(List<Short> values) {
            addCriterion("FCREATEUSERID in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotIn(List<Short> values) {
            addCriterion("FCREATEUSERID not in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridBetween(Short value1, Short value2) {
            addCriterion("FCREATEUSERID between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotBetween(Short value1, Short value2) {
            addCriterion("FCREATEUSERID not between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeIsNull() {
            addCriterion("FLASTUPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeIsNotNull() {
            addCriterion("FLASTUPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeEqualTo(Date value) {
            addCriterion("FLASTUPDATETIME =", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeNotEqualTo(Date value) {
            addCriterion("FLASTUPDATETIME <>", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeGreaterThan(Date value) {
            addCriterion("FLASTUPDATETIME >", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FLASTUPDATETIME >=", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeLessThan(Date value) {
            addCriterion("FLASTUPDATETIME <", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("FLASTUPDATETIME <=", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeIn(List<Date> values) {
            addCriterion("FLASTUPDATETIME in", values, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeNotIn(List<Date> values) {
            addCriterion("FLASTUPDATETIME not in", values, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeBetween(Date value1, Date value2) {
            addCriterion("FLASTUPDATETIME between", value1, value2, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("FLASTUPDATETIME not between", value1, value2, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridIsNull() {
            addCriterion("FLASTMODIFYUSERID is null");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridIsNotNull() {
            addCriterion("FLASTMODIFYUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridEqualTo(Short value) {
            addCriterion("FLASTMODIFYUSERID =", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridNotEqualTo(Short value) {
            addCriterion("FLASTMODIFYUSERID <>", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridGreaterThan(Short value) {
            addCriterion("FLASTMODIFYUSERID >", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridGreaterThanOrEqualTo(Short value) {
            addCriterion("FLASTMODIFYUSERID >=", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridLessThan(Short value) {
            addCriterion("FLASTMODIFYUSERID <", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridLessThanOrEqualTo(Short value) {
            addCriterion("FLASTMODIFYUSERID <=", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridIn(List<Short> values) {
            addCriterion("FLASTMODIFYUSERID in", values, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridNotIn(List<Short> values) {
            addCriterion("FLASTMODIFYUSERID not in", values, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridBetween(Short value1, Short value2) {
            addCriterion("FLASTMODIFYUSERID between", value1, value2, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridNotBetween(Short value1, Short value2) {
            addCriterion("FLASTMODIFYUSERID not between", value1, value2, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNull() {
            addCriterion("FCONTRACTID is null");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNotNull() {
            addCriterion("FCONTRACTID is not null");
            return (Criteria) this;
        }

        public Criteria andFcontractidEqualTo(Short value) {
            addCriterion("FCONTRACTID =", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotEqualTo(Short value) {
            addCriterion("FCONTRACTID <>", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThan(Short value) {
            addCriterion("FCONTRACTID >", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThanOrEqualTo(Short value) {
            addCriterion("FCONTRACTID >=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThan(Short value) {
            addCriterion("FCONTRACTID <", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThanOrEqualTo(Short value) {
            addCriterion("FCONTRACTID <=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIn(List<Short> values) {
            addCriterion("FCONTRACTID in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotIn(List<Short> values) {
            addCriterion("FCONTRACTID not in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidBetween(Short value1, Short value2) {
            addCriterion("FCONTRACTID between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotBetween(Short value1, Short value2) {
            addCriterion("FCONTRACTID not between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFchargerebateIsNull() {
            addCriterion("FCHARGEREBATE is null");
            return (Criteria) this;
        }

        public Criteria andFchargerebateIsNotNull() {
            addCriterion("FCHARGEREBATE is not null");
            return (Criteria) this;
        }

        public Criteria andFchargerebateEqualTo(BigDecimal value) {
            addCriterion("FCHARGEREBATE =", value, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateNotEqualTo(BigDecimal value) {
            addCriterion("FCHARGEREBATE <>", value, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateGreaterThan(BigDecimal value) {
            addCriterion("FCHARGEREBATE >", value, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FCHARGEREBATE >=", value, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateLessThan(BigDecimal value) {
            addCriterion("FCHARGEREBATE <", value, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FCHARGEREBATE <=", value, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateIn(List<BigDecimal> values) {
            addCriterion("FCHARGEREBATE in", values, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateNotIn(List<BigDecimal> values) {
            addCriterion("FCHARGEREBATE not in", values, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FCHARGEREBATE between", value1, value2, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFchargerebateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FCHARGEREBATE not between", value1, value2, "fchargerebate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateIsNull() {
            addCriterion("FAGENTGATHRATE is null");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateIsNotNull() {
            addCriterion("FAGENTGATHRATE is not null");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateEqualTo(BigDecimal value) {
            addCriterion("FAGENTGATHRATE =", value, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateNotEqualTo(BigDecimal value) {
            addCriterion("FAGENTGATHRATE <>", value, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateGreaterThan(BigDecimal value) {
            addCriterion("FAGENTGATHRATE >", value, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FAGENTGATHRATE >=", value, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateLessThan(BigDecimal value) {
            addCriterion("FAGENTGATHRATE <", value, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FAGENTGATHRATE <=", value, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateIn(List<BigDecimal> values) {
            addCriterion("FAGENTGATHRATE in", values, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateNotIn(List<BigDecimal> values) {
            addCriterion("FAGENTGATHRATE not in", values, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAGENTGATHRATE between", value1, value2, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFagentgathrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAGENTGATHRATE not between", value1, value2, "fagentgathrate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateIsNull() {
            addCriterion("FINSUREDPRICERATE is null");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateIsNotNull() {
            addCriterion("FINSUREDPRICERATE is not null");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateEqualTo(BigDecimal value) {
            addCriterion("FINSUREDPRICERATE =", value, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateNotEqualTo(BigDecimal value) {
            addCriterion("FINSUREDPRICERATE <>", value, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateGreaterThan(BigDecimal value) {
            addCriterion("FINSUREDPRICERATE >", value, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FINSUREDPRICERATE >=", value, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateLessThan(BigDecimal value) {
            addCriterion("FINSUREDPRICERATE <", value, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FINSUREDPRICERATE <=", value, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateIn(List<BigDecimal> values) {
            addCriterion("FINSUREDPRICERATE in", values, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateNotIn(List<BigDecimal> values) {
            addCriterion("FINSUREDPRICERATE not in", values, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FINSUREDPRICERATE between", value1, value2, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFinsuredpricerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FINSUREDPRICERATE not between", value1, value2, "finsuredpricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateIsNull() {
            addCriterion("FRECEIVEPRICERATE is null");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateIsNotNull() {
            addCriterion("FRECEIVEPRICERATE is not null");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateEqualTo(BigDecimal value) {
            addCriterion("FRECEIVEPRICERATE =", value, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateNotEqualTo(BigDecimal value) {
            addCriterion("FRECEIVEPRICERATE <>", value, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateGreaterThan(BigDecimal value) {
            addCriterion("FRECEIVEPRICERATE >", value, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FRECEIVEPRICERATE >=", value, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateLessThan(BigDecimal value) {
            addCriterion("FRECEIVEPRICERATE <", value, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FRECEIVEPRICERATE <=", value, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateIn(List<BigDecimal> values) {
            addCriterion("FRECEIVEPRICERATE in", values, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateNotIn(List<BigDecimal> values) {
            addCriterion("FRECEIVEPRICERATE not in", values, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FRECEIVEPRICERATE between", value1, value2, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFreceivepricerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FRECEIVEPRICERATE not between", value1, value2, "freceivepricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateIsNull() {
            addCriterion("FDELIVERYPRICERATE is null");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateIsNotNull() {
            addCriterion("FDELIVERYPRICERATE is not null");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateEqualTo(BigDecimal value) {
            addCriterion("FDELIVERYPRICERATE =", value, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateNotEqualTo(BigDecimal value) {
            addCriterion("FDELIVERYPRICERATE <>", value, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateGreaterThan(BigDecimal value) {
            addCriterion("FDELIVERYPRICERATE >", value, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FDELIVERYPRICERATE >=", value, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateLessThan(BigDecimal value) {
            addCriterion("FDELIVERYPRICERATE <", value, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FDELIVERYPRICERATE <=", value, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateIn(List<BigDecimal> values) {
            addCriterion("FDELIVERYPRICERATE in", values, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateNotIn(List<BigDecimal> values) {
            addCriterion("FDELIVERYPRICERATE not in", values, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FDELIVERYPRICERATE between", value1, value2, "fdeliverypricerate");
            return (Criteria) this;
        }

        public Criteria andFdeliverypricerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FDELIVERYPRICERATE not between", value1, value2, "fdeliverypricerate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated do_not_delete_during_merge Tue May 29 20:34:45 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}