package com.deppon.crm.module.client.sync.dao.impl;

import com.deppon.crm.module.client.sync.dao.impl.TCustPreferentialExample;
import com.deppon.crm.module.client.sync.domain.dto.TCustPreferential;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCustPreferentialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int countByExample(TCustPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int deleteByExample(TCustPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int deleteByPrimaryKey(Short fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int insert(TCustPreferential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int insertSelective(TCustPreferential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    List<TCustPreferential> selectByExample(TCustPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    TCustPreferential selectByPrimaryKey(Short fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int updateByExampleSelective(@Param("record") TCustPreferential record, @Param("example") TCustPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int updateByExample(@Param("record") TCustPreferential record, @Param("example") TCustPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int updateByPrimaryKeySelective(TCustPreferential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_PREFERENTIAL
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int updateByPrimaryKey(TCustPreferential record);
}