package com.deppon.crm.module.client.sync.dao.impl;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCustContractdeptExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public TCustContractdeptExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFidIsNull() {
            addCriterion("FID is null");
            return (Criteria) this;
        }

        public Criteria andFidIsNotNull() {
            addCriterion("FID is not null");
            return (Criteria) this;
        }

        public Criteria andFidEqualTo(Short value) {
            addCriterion("FID =", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotEqualTo(Short value) {
            addCriterion("FID <>", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThan(Short value) {
            addCriterion("FID >", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThanOrEqualTo(Short value) {
            addCriterion("FID >=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThan(Short value) {
            addCriterion("FID <", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThanOrEqualTo(Short value) {
            addCriterion("FID <=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidIn(List<Short> values) {
            addCriterion("FID in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotIn(List<Short> values) {
            addCriterion("FID not in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidBetween(Short value1, Short value2) {
            addCriterion("FID between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotBetween(Short value1, Short value2) {
            addCriterion("FID not between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNull() {
            addCriterion("FCREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIsNotNull() {
            addCriterion("FCREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeEqualTo(Date value) {
            addCriterion("FCREATETIME =", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotEqualTo(Date value) {
            addCriterion("FCREATETIME <>", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThan(Date value) {
            addCriterion("FCREATETIME >", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FCREATETIME >=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThan(Date value) {
            addCriterion("FCREATETIME <", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("FCREATETIME <=", value, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeIn(List<Date> values) {
            addCriterion("FCREATETIME in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotIn(List<Date> values) {
            addCriterion("FCREATETIME not in", values, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeBetween(Date value1, Date value2) {
            addCriterion("FCREATETIME between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("FCREATETIME not between", value1, value2, "fcreatetime");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNull() {
            addCriterion("FCREATEUSERID is null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIsNotNull() {
            addCriterion("FCREATEUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridEqualTo(Short value) {
            addCriterion("FCREATEUSERID =", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotEqualTo(Short value) {
            addCriterion("FCREATEUSERID <>", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThan(Short value) {
            addCriterion("FCREATEUSERID >", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridGreaterThanOrEqualTo(Short value) {
            addCriterion("FCREATEUSERID >=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThan(Short value) {
            addCriterion("FCREATEUSERID <", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridLessThanOrEqualTo(Short value) {
            addCriterion("FCREATEUSERID <=", value, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridIn(List<Short> values) {
            addCriterion("FCREATEUSERID in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotIn(List<Short> values) {
            addCriterion("FCREATEUSERID not in", values, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridBetween(Short value1, Short value2) {
            addCriterion("FCREATEUSERID between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFcreateuseridNotBetween(Short value1, Short value2) {
            addCriterion("FCREATEUSERID not between", value1, value2, "fcreateuserid");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeIsNull() {
            addCriterion("FLASTUPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeIsNotNull() {
            addCriterion("FLASTUPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeEqualTo(Date value) {
            addCriterion("FLASTUPDATETIME =", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeNotEqualTo(Date value) {
            addCriterion("FLASTUPDATETIME <>", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeGreaterThan(Date value) {
            addCriterion("FLASTUPDATETIME >", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FLASTUPDATETIME >=", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeLessThan(Date value) {
            addCriterion("FLASTUPDATETIME <", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("FLASTUPDATETIME <=", value, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeIn(List<Date> values) {
            addCriterion("FLASTUPDATETIME in", values, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeNotIn(List<Date> values) {
            addCriterion("FLASTUPDATETIME not in", values, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeBetween(Date value1, Date value2) {
            addCriterion("FLASTUPDATETIME between", value1, value2, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("FLASTUPDATETIME not between", value1, value2, "flastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridIsNull() {
            addCriterion("FLASTMODIFYUSERID is null");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridIsNotNull() {
            addCriterion("FLASTMODIFYUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridEqualTo(Short value) {
            addCriterion("FLASTMODIFYUSERID =", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridNotEqualTo(Short value) {
            addCriterion("FLASTMODIFYUSERID <>", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridGreaterThan(Short value) {
            addCriterion("FLASTMODIFYUSERID >", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridGreaterThanOrEqualTo(Short value) {
            addCriterion("FLASTMODIFYUSERID >=", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridLessThan(Short value) {
            addCriterion("FLASTMODIFYUSERID <", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridLessThanOrEqualTo(Short value) {
            addCriterion("FLASTMODIFYUSERID <=", value, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridIn(List<Short> values) {
            addCriterion("FLASTMODIFYUSERID in", values, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridNotIn(List<Short> values) {
            addCriterion("FLASTMODIFYUSERID not in", values, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridBetween(Short value1, Short value2) {
            addCriterion("FLASTMODIFYUSERID between", value1, value2, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFlastmodifyuseridNotBetween(Short value1, Short value2) {
            addCriterion("FLASTMODIFYUSERID not between", value1, value2, "flastmodifyuserid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNull() {
            addCriterion("FCONTRACTID is null");
            return (Criteria) this;
        }

        public Criteria andFcontractidIsNotNull() {
            addCriterion("FCONTRACTID is not null");
            return (Criteria) this;
        }

        public Criteria andFcontractidEqualTo(Short value) {
            addCriterion("FCONTRACTID =", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotEqualTo(Short value) {
            addCriterion("FCONTRACTID <>", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThan(Short value) {
            addCriterion("FCONTRACTID >", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidGreaterThanOrEqualTo(Short value) {
            addCriterion("FCONTRACTID >=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThan(Short value) {
            addCriterion("FCONTRACTID <", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidLessThanOrEqualTo(Short value) {
            addCriterion("FCONTRACTID <=", value, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidIn(List<Short> values) {
            addCriterion("FCONTRACTID in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotIn(List<Short> values) {
            addCriterion("FCONTRACTID not in", values, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidBetween(Short value1, Short value2) {
            addCriterion("FCONTRACTID between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFcontractidNotBetween(Short value1, Short value2) {
            addCriterion("FCONTRACTID not between", value1, value2, "fcontractid");
            return (Criteria) this;
        }

        public Criteria andFdeptidIsNull() {
            addCriterion("FDEPTID is null");
            return (Criteria) this;
        }

        public Criteria andFdeptidIsNotNull() {
            addCriterion("FDEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andFdeptidEqualTo(Short value) {
            addCriterion("FDEPTID =", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidNotEqualTo(Short value) {
            addCriterion("FDEPTID <>", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidGreaterThan(Short value) {
            addCriterion("FDEPTID >", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidGreaterThanOrEqualTo(Short value) {
            addCriterion("FDEPTID >=", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidLessThan(Short value) {
            addCriterion("FDEPTID <", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidLessThanOrEqualTo(Short value) {
            addCriterion("FDEPTID <=", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidIn(List<Short> values) {
            addCriterion("FDEPTID in", values, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidNotIn(List<Short> values) {
            addCriterion("FDEPTID not in", values, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidBetween(Short value1, Short value2) {
            addCriterion("FDEPTID between", value1, value2, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidNotBetween(Short value1, Short value2) {
            addCriterion("FDEPTID not between", value1, value2, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFbegintimeIsNull() {
            addCriterion("FBEGINTIME is null");
            return (Criteria) this;
        }

        public Criteria andFbegintimeIsNotNull() {
            addCriterion("FBEGINTIME is not null");
            return (Criteria) this;
        }

        public Criteria andFbegintimeEqualTo(Date value) {
            addCriterion("FBEGINTIME =", value, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeNotEqualTo(Date value) {
            addCriterion("FBEGINTIME <>", value, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeGreaterThan(Date value) {
            addCriterion("FBEGINTIME >", value, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FBEGINTIME >=", value, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeLessThan(Date value) {
            addCriterion("FBEGINTIME <", value, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeLessThanOrEqualTo(Date value) {
            addCriterion("FBEGINTIME <=", value, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeIn(List<Date> values) {
            addCriterion("FBEGINTIME in", values, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeNotIn(List<Date> values) {
            addCriterion("FBEGINTIME not in", values, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeBetween(Date value1, Date value2) {
            addCriterion("FBEGINTIME between", value1, value2, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFbegintimeNotBetween(Date value1, Date value2) {
            addCriterion("FBEGINTIME not between", value1, value2, "fbegintime");
            return (Criteria) this;
        }

        public Criteria andFendtimeIsNull() {
            addCriterion("FENDTIME is null");
            return (Criteria) this;
        }

        public Criteria andFendtimeIsNotNull() {
            addCriterion("FENDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andFendtimeEqualTo(Date value) {
            addCriterion("FENDTIME =", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeNotEqualTo(Date value) {
            addCriterion("FENDTIME <>", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeGreaterThan(Date value) {
            addCriterion("FENDTIME >", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FENDTIME >=", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeLessThan(Date value) {
            addCriterion("FENDTIME <", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeLessThanOrEqualTo(Date value) {
            addCriterion("FENDTIME <=", value, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeIn(List<Date> values) {
            addCriterion("FENDTIME in", values, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeNotIn(List<Date> values) {
            addCriterion("FENDTIME not in", values, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeBetween(Date value1, Date value2) {
            addCriterion("FENDTIME between", value1, value2, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFendtimeNotBetween(Date value1, Date value2) {
            addCriterion("FENDTIME not between", value1, value2, "fendtime");
            return (Criteria) this;
        }

        public Criteria andFworkflowidIsNull() {
            addCriterion("FWORKFLOWID is null");
            return (Criteria) this;
        }

        public Criteria andFworkflowidIsNotNull() {
            addCriterion("FWORKFLOWID is not null");
            return (Criteria) this;
        }

        public Criteria andFworkflowidEqualTo(String value) {
            addCriterion("FWORKFLOWID =", value, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidNotEqualTo(String value) {
            addCriterion("FWORKFLOWID <>", value, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidGreaterThan(String value) {
            addCriterion("FWORKFLOWID >", value, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidGreaterThanOrEqualTo(String value) {
            addCriterion("FWORKFLOWID >=", value, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidLessThan(String value) {
            addCriterion("FWORKFLOWID <", value, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidLessThanOrEqualTo(String value) {
            addCriterion("FWORKFLOWID <=", value, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidLike(String value) {
            addCriterion("FWORKFLOWID like", value, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidNotLike(String value) {
            addCriterion("FWORKFLOWID not like", value, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidIn(List<String> values) {
            addCriterion("FWORKFLOWID in", values, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidNotIn(List<String> values) {
            addCriterion("FWORKFLOWID not in", values, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidBetween(String value1, String value2) {
            addCriterion("FWORKFLOWID between", value1, value2, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFworkflowidNotBetween(String value1, String value2) {
            addCriterion("FWORKFLOWID not between", value1, value2, "fworkflowid");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanIsNull() {
            addCriterion("FAPPROVALMAN is null");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanIsNotNull() {
            addCriterion("FAPPROVALMAN is not null");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanEqualTo(String value) {
            addCriterion("FAPPROVALMAN =", value, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanNotEqualTo(String value) {
            addCriterion("FAPPROVALMAN <>", value, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanGreaterThan(String value) {
            addCriterion("FAPPROVALMAN >", value, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanGreaterThanOrEqualTo(String value) {
            addCriterion("FAPPROVALMAN >=", value, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanLessThan(String value) {
            addCriterion("FAPPROVALMAN <", value, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanLessThanOrEqualTo(String value) {
            addCriterion("FAPPROVALMAN <=", value, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanLike(String value) {
            addCriterion("FAPPROVALMAN like", value, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanNotLike(String value) {
            addCriterion("FAPPROVALMAN not like", value, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanIn(List<String> values) {
            addCriterion("FAPPROVALMAN in", values, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanNotIn(List<String> values) {
            addCriterion("FAPPROVALMAN not in", values, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanBetween(String value1, String value2) {
            addCriterion("FAPPROVALMAN between", value1, value2, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFapprovalmanNotBetween(String value1, String value2) {
            addCriterion("FAPPROVALMAN not between", value1, value2, "fapprovalman");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeIsNull() {
            addCriterion("FWORKFLOWTYPE is null");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeIsNotNull() {
            addCriterion("FWORKFLOWTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeEqualTo(String value) {
            addCriterion("FWORKFLOWTYPE =", value, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeNotEqualTo(String value) {
            addCriterion("FWORKFLOWTYPE <>", value, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeGreaterThan(String value) {
            addCriterion("FWORKFLOWTYPE >", value, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeGreaterThanOrEqualTo(String value) {
            addCriterion("FWORKFLOWTYPE >=", value, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeLessThan(String value) {
            addCriterion("FWORKFLOWTYPE <", value, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeLessThanOrEqualTo(String value) {
            addCriterion("FWORKFLOWTYPE <=", value, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeLike(String value) {
            addCriterion("FWORKFLOWTYPE like", value, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeNotLike(String value) {
            addCriterion("FWORKFLOWTYPE not like", value, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeIn(List<String> values) {
            addCriterion("FWORKFLOWTYPE in", values, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeNotIn(List<String> values) {
            addCriterion("FWORKFLOWTYPE not in", values, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeBetween(String value1, String value2) {
            addCriterion("FWORKFLOWTYPE between", value1, value2, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFworkflowtypeNotBetween(String value1, String value2) {
            addCriterion("FWORKFLOWTYPE not between", value1, value2, "fworkflowtype");
            return (Criteria) this;
        }

        public Criteria andFisdeptIsNull() {
            addCriterion("FISDEPT is null");
            return (Criteria) this;
        }

        public Criteria andFisdeptIsNotNull() {
            addCriterion("FISDEPT is not null");
            return (Criteria) this;
        }

        public Criteria andFisdeptEqualTo(String value) {
            addCriterion("FISDEPT =", value, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptNotEqualTo(String value) {
            addCriterion("FISDEPT <>", value, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptGreaterThan(String value) {
            addCriterion("FISDEPT >", value, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptGreaterThanOrEqualTo(String value) {
            addCriterion("FISDEPT >=", value, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptLessThan(String value) {
            addCriterion("FISDEPT <", value, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptLessThanOrEqualTo(String value) {
            addCriterion("FISDEPT <=", value, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptLike(String value) {
            addCriterion("FISDEPT like", value, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptNotLike(String value) {
            addCriterion("FISDEPT not like", value, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptIn(List<String> values) {
            addCriterion("FISDEPT in", values, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptNotIn(List<String> values) {
            addCriterion("FISDEPT not in", values, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptBetween(String value1, String value2) {
            addCriterion("FISDEPT between", value1, value2, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFisdeptNotBetween(String value1, String value2) {
            addCriterion("FISDEPT not between", value1, value2, "fisdept");
            return (Criteria) this;
        }

        public Criteria andFstateIsNull() {
            addCriterion("FSTATE is null");
            return (Criteria) this;
        }

        public Criteria andFstateIsNotNull() {
            addCriterion("FSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andFstateEqualTo(String value) {
            addCriterion("FSTATE =", value, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateNotEqualTo(String value) {
            addCriterion("FSTATE <>", value, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateGreaterThan(String value) {
            addCriterion("FSTATE >", value, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateGreaterThanOrEqualTo(String value) {
            addCriterion("FSTATE >=", value, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateLessThan(String value) {
            addCriterion("FSTATE <", value, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateLessThanOrEqualTo(String value) {
            addCriterion("FSTATE <=", value, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateLike(String value) {
            addCriterion("FSTATE like", value, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateNotLike(String value) {
            addCriterion("FSTATE not like", value, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateIn(List<String> values) {
            addCriterion("FSTATE in", values, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateNotIn(List<String> values) {
            addCriterion("FSTATE not in", values, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateBetween(String value1, String value2) {
            addCriterion("FSTATE between", value1, value2, "fstate");
            return (Criteria) this;
        }

        public Criteria andFstateNotBetween(String value1, String value2) {
            addCriterion("FSTATE not between", value1, value2, "fstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateIsNull() {
            addCriterion("FAPPROVALSTATE is null");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateIsNotNull() {
            addCriterion("FAPPROVALSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateEqualTo(String value) {
            addCriterion("FAPPROVALSTATE =", value, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateNotEqualTo(String value) {
            addCriterion("FAPPROVALSTATE <>", value, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateGreaterThan(String value) {
            addCriterion("FAPPROVALSTATE >", value, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateGreaterThanOrEqualTo(String value) {
            addCriterion("FAPPROVALSTATE >=", value, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateLessThan(String value) {
            addCriterion("FAPPROVALSTATE <", value, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateLessThanOrEqualTo(String value) {
            addCriterion("FAPPROVALSTATE <=", value, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateLike(String value) {
            addCriterion("FAPPROVALSTATE like", value, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateNotLike(String value) {
            addCriterion("FAPPROVALSTATE not like", value, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateIn(List<String> values) {
            addCriterion("FAPPROVALSTATE in", values, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateNotIn(List<String> values) {
            addCriterion("FAPPROVALSTATE not in", values, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateBetween(String value1, String value2) {
            addCriterion("FAPPROVALSTATE between", value1, value2, "fapprovalstate");
            return (Criteria) this;
        }

        public Criteria andFapprovalstateNotBetween(String value1, String value2) {
            addCriterion("FAPPROVALSTATE not between", value1, value2, "fapprovalstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated do_not_delete_during_merge Tue May 29 20:34:45 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}