package com.deppon.crm.module.client.sync.dao.impl;

import com.deppon.crm.module.client.sync.dao.impl.TCustContractdeptExample;
import com.deppon.crm.module.client.sync.domain.dto.TCustContractdept;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCustContractdeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int countByExample(TCustContractdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int deleteByExample(TCustContractdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int deleteByPrimaryKey(Short fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int insert(TCustContractdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int insertSelective(TCustContractdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    List<TCustContractdept> selectByExample(TCustContractdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    TCustContractdept selectByPrimaryKey(Short fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int updateByExampleSelective(@Param("record") TCustContractdept record, @Param("example") TCustContractdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int updateByExample(@Param("record") TCustContractdept record, @Param("example") TCustContractdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int updateByPrimaryKeySelective(TCustContractdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACTDEPT
     *
     * @mbggenerated Tue May 29 20:34:45 CST 2012
     */
    int updateByPrimaryKey(TCustContractdept record);
}