package com.deppon.crm.module.client.sync.dao.impl;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.deppon.crm.module.client.sync.domain.dto.TCustContract;

public interface TCustContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int countByExample(TCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int deleteByExample(TCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int deleteByPrimaryKey(Short fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int insert(TCustContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int insertSelective(TCustContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    List<TCustContract> selectByExample(TCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    TCustContract selectByPrimaryKey(Short fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int updateByExampleSelective(@Param("record") TCustContract record, @Param("example") TCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int updateByExample(@Param("record") TCustContract record, @Param("example") TCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int updateByPrimaryKeySelective(TCustContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVELOP.T_CUST_CONTRACT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    int updateByPrimaryKey(TCustContract record);
}