package com.deppon.crm.module.client.sync.dao.impl;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.deppon.crm.module.client.sync.domain.dto.TCustShuttleaddress;

public interface TCustShuttleaddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int countByExample(TCustShuttleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int deleteByExample(TCustShuttleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int deleteByPrimaryKey(Short fid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int insert(TCustShuttleaddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int insertSelective(TCustShuttleaddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	List<TCustShuttleaddress> selectByExample(TCustShuttleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	TCustShuttleaddress selectByPrimaryKey(Short fid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int updateByExampleSelective(@Param("record") TCustShuttleaddress record,
			@Param("example") TCustShuttleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int updateByExample(@Param("record") TCustShuttleaddress record,
			@Param("example") TCustShuttleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int updateByPrimaryKeySelective(TCustShuttleaddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVELOP.T_CUST_SHUTTLEADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	int updateByPrimaryKey(TCustShuttleaddress record);
}