package com.deppon.crm.module.interfaces.fin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.deppon.crm.module.interfaces.fin.domain.NotifyClaimsStateRequest;
import com.deppon.crm.module.interfaces.fin.domain.NotifyClaimsStateResponse;
import com.deppon.crm.module.interfaces.fin.domain.ObjectFactory;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-24T19:11:32.937+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://notifyclaims.fin.interfaces.module.crm.deppon.com", name = "ICrmNotifyClaimsService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ICrmNotifyClaimsService {

    @WebResult(name = "notify_claims_stateResponse", targetNamespace = "http://www.deppon.com/fssc/remote/crm/domain/entity", partName = "Notify_claims_stateResponse")
    @WebMethod
    public NotifyClaimsStateResponse notifyClaimState(
        @WebParam(partName = "Notify_claims_stateRequest", name = "notify_claims_stateRequest", targetNamespace = "http://www.deppon.com/fssc/remote/crm/domain/entity")
        NotifyClaimsStateRequest notifyClaimsStateRequest
    );
}
