package com.deppon.crm.module.common.shared.domain;

/**
 * @作者：罗典
 * @时间：2012-3-12
 * @功能：数据字典类型枚举，根据此值可以查询对应下拉框列表值
 * */
public enum DataHeadTypeEnum {
	//账户性质
	ACCOUNT_NATURE("账户性质"),
	//账号性质_散客
	ACCOUNT_NATURE_SC("账号性质_散客"),
	//账户性质
	ACCOUNT_PROPERTIES("账户性质"),
	//账户用途
	ACCOUNT_USE("账户用途"),
	//活动类别
	ACTIVITY_CATEGORY("活动类别"),
	//活动条件类型
	ACTIVITY_CONDITION("活动条件类型"),
	//活动关联类型
	ACTIVITY_RELATION("活动关联类型"),
	//活动状态
	ACTIVITY_STATUS("活动状态"),
	//活动类型
	ACTIVITY_TYPE("活动类型"),
	//地址类型
	ADDRESS_TYPE("地址类型"),
	//阿里巴巴会员类型
	ALIBABA_MEMBERTYPE("阿里巴巴会员类型"),
	//审批依据
	APPROVAL_ACCORDING("审批依据"),
	//工作流审批结果
	APPROVE_REUSLT("工作流审批结果"),
	//申请延时
	ASK_DELAYED("申请延时"),
	//关联状态
	ASSOCITION_STATUS("关联状态"),
	//奖罚对象类型
	AWARD_TARGET_TYPE("奖罚对象类型"),
	//奖罚类型
	AWARD_TYPE("奖罚类型"),
	//申请状态
	BACKFREIGHT_AAPLY_TYPE("申请状态"),
	//付款方式
	BACKFREIGHT_PAY_TYPE("付款方式"),
	//运输性质
	BACKFREIGHT_TRANSPORT_TYPE("运输性质"),
	//发票要求
	BILL_REQUIRE("发票要求"),
	//商机关闭原因
	BO_CLOSE_REASON("商机关闭原因"),
	//商机状态
	BUSINESS_OPPORTUNITY_STATUS("商机状态"),
	//商机阶段
	BUSINESS_OPPORTUNITY_STEP("商机阶段"),
	//来电人类型
	CALLER_TYPE("来电人类型"),
	//证件类型个人联系人
	CARDTYPECON("证件类型个人联系人"),
	//证件类型新增和修改普通权限
	CARDTYPECON_AU("证件类型新增和修改普通权限"),
	//证件类型新增和修改
	CARDTYPECON_NOTVIEW("证件类型新增和修改"),
	//证件类型企业
	CARDTYPECUST("证件类型企业"),
	//货量潜力类型
	CARGO_POTENTIAL("货量潜力类型"),
	//索赔状态
	CLAIM_STATUS("索赔状态"),
	//理赔工作流状态
	CLAIM_WORKFLOW_STATE("理赔工作流状态"),
	//客户群提货方式
	CLIENTBASE_PICKUPGOODS("客户群提货方式"),
	//客户群产品类型
	CLIENTBASE_PRODUCT_TYPE("客户群产品类型"),
	//计划日程来源
	COME_FROM("计划日程来源"),
	//投诉人
	COMPLAINANT("投诉人"),
	//业务模式
	COMPLAINT_BUSINESS_MODEL("业务模式"),
	//查询客户工单
	COMPLAINT_FIELD("查询客户工单"),
	//投诉级别
	COMPLAINT_GRADE("投诉级别"),
	//投诉级别
	COMPLAINT_LEVEL("投诉级别"),
	//投诉环节
	//投诉环节
	COMPLAINT_LINK("投诉环节"),
	//工单模块处理状态
	COMPLAINT_PROCESS_STATUS("工单模块处理状态"),
	//工单模块反馈类型
	COMPLAINT_RECORD_TYPE("工单模块反馈类型"),
	//投诉方式
	COMPLAINT_WAY("投诉方式"),
	//公司性质
	COMP_NATURE("公司性质"),
	//始发网点与受理部门是否接货
	CONFIG_ORDER_RECEIVE_GOODS("始发网点与受理部门是否接货"),
	//始发网点与受理部门订单来源
	CONFIG_ORDER_SOURCE("始发网点与受理部门订单来源"),
	//合同状态
	CONTACT_STATUS("合同状态"),
	//继续营销
	CONTINUE_MARKET("继续营销"),
	//合同附件
	CONTRACT_ANNEX("合同附件"),
	//合同工作流状态
	CONTRACT_WORKFLOW_STATUS("合同工作流状态"),
	//合同流程类型
	CONTRACT_WORKFLOW_TYPE("合同流程类型"),
	//合作意向
	COOPERATION_INTENTION("合作意向"),
	//合作物流
	COOPERATION_LOGISTICS("合作物流"),
	//手动优惠券活动类型
	COUPON_ACTIVITY_TYPE("手动优惠券活动类型"),
	//金额要求
	COUPON_AMOUNT_TYPE("金额要求"),
	//增值费
	COUPON_APPRECIATION_TYPE("增值费"),
	//费用类型
	COUPON_COST_TYPE("费用类型"),
	//优惠券来源
	COUPON_RESOURCE("优惠券来源"),
	//客户类别(五公里地图)
	CUSTOMER_CATEGORY("客户类别(五公里地图)"),
	//客户类别（回访录入查询）
	CUSTOMER_CATEGORY_TYPE("客户类别（回访录入查询）"),
	//客户意见
	CUSTOMER_IDEA("客户意见"),
	//客户属性
	CUSTOMER_NATURE("客户属性"),
	//客户性质
	CUSTOMER_TYPE("客户性质"),
	//客户类别
	CUST_CATEGORY("客户类别"),
	//客户群状态
	CUST_CONDITION_STATUS("客户群状态"),
	//客户领款方式
	CUST_DROWMONEY_TYPE("客户领款方式"),
	//线路
	CUST_LINE("线路"),
	//奖励类型
	CUST_RULETYPE("奖励类型"),
	//礼品发放状态
	CUST_SEND_STATUS("礼品发放状态"),
	//客户来源
	CUST_SOURCE("客户来源"),
	//客户类型(开发日程/开发计划)
	CUST_TYPE("客户类型(开发日程/开发计划)"),
	//出险类型
	DANGER_TYPE("出险类型"),
	//解决情况
	DELAY_APPLY("解决情况"),
	//开发依据
	DEVELOP_ACCORDING("开发依据"),
	//开发阶段
	DEVELOP_STAGE("开发阶段"),
	//开发状态
	DEVELOP_STATUS("开发状态"),
	//开发方式
	DEVELOP_WAY("开发方式"),
	//开发和维护计划类型
	DEV_MAT_PLANTYPE("开发和维护计划类型"),
	//优惠产品
	DISCOUNT_PRODUCTS("优惠产品"),
	//工单责任投诉环节
	DUTY_COMPLAINT_LINK("工单责任投诉环节"),
	//工单责任状态
	DUTY_RESULT_STATUS("工单责任状态"),
	//调查结果
	DUTY_SURVEY_RESULT("调查结果"),
	//工单责任总调查结果
	DUTY_TOTAL_SURVEY_RESULT("工单责任总调查结果"),
	//期望时限
	EXPECTED_TIME_LIMIT("期望时限"),
	//快递业务的产品类型
	EXPRESS_PRODUCT_TYPE("快递业务的产品类型"),
	//快递合同优惠类型
	EXPRIVILEGE_TYPE("快递合同优惠类型"),
	//反馈信息
	FEEDBACK_INFO("反馈信息"),
	//公司规模
	FIRM_SIZE("公司规模"),
	//产品类型
	FOSS_PRODUCT_TYPE("产品类型"),
	//货物类型
	GARGO_TYPE("货物类型"),
	//性别
	GENDER("性别"),
	//奖励类型
	INTEG_AWARD_TYPE("奖励类型"),
	//发票标记
	INVOICE_MARK("发票标记"),
	//大客户工作流类型
	KEYCUST_WORKFLOW_TYPE("大客户工作流类型"),
	//活动线路区域要求
	LINE_TYPE("活动线路区域要求"),
	//联系人属性
	LINKMAN_TYPE("联系人属性"),
	//物流决定权
	LOGIST_DECI("物流决定权"),
	//流失原因
	LOSS_REASON("流失原因"),
	//维护方式
	MAINTAIN_WAY("维护方式"),
	//品名行业映射状态
	MAPPING_ITEM_STATUS("品名行业映射状态"),
	//地图标记
	MAP_MAKER_STATUS("地图标记"),
	//是否接受营销信息
	MARKETINFO("是否接受营销信息"),
	//会员等级
	MEMBER_GRADE("会员等级"),
	//消息提醒
	MESSAGE_REMIND("消息提醒"),
	//公告类型
	//公告类型
	NOTICE_TYPE("公告类型"),
	//目前级别(会员升级列表)
	NOW_GRAD_UP("目前级别(会员升级列表)"),
	//在线理赔监控_索赔金额
	ONLINEAPPLY_AMOUNT("在线理赔监控_索赔金额"),
	//在线理赔状态
	ONLINEAPPLY_STATUS("在线理赔状态"),
	//操作类型
	OPERATE_TYPE("操作类型"),
	//订单操作
	ORDER_OPERATION("订单操作"),
	//订单来源
	ORDER_SOURCE("订单来源"),
	//订单状态
	ORDER_STATUS("订单状态"),
	//付款方式(理赔模块)
	PAY_METHOD("付款方式(理赔模块)"),
	//付款方式(订单模块)
	PAY_WAY("付款方式(订单模块)"),
	//送货方式
	PICKGOODTYPE("送货方式"),
	//计划状态
	PLAN_STATUS("计划状态"),
	//计划类别
	PLAN_TYPE("计划类别"),
	//偏好渠道
	PREFERENCE_CHANNEL("偏好渠道"),
	//偏好服务
	PREFERENCE_SERVICE("偏好服务"),
	//优惠方式
	PREFERENTIAL_WAY("优惠方式"),
	//优先级别
	PRIORITY_RATING("优先级别"),
	//优惠类型
	PRIVILEGE_TYPE("优惠类型"),
	//处理类型
	PROCESS_TYPE("处理类型"),
	//问题类型
	QUESTION_TYPE("问题类型"),
	//结款方式
	RECKON_WAY("结款方式"),
	//理赔状态
	RECOMPENSE_STATUS("理赔状态"),
	//理赔类型
	RECOMPENSE_TYPE("理赔类型"),
	//理赔方式
	RECOMPENSE_WAY("理赔方式"),
	//理赔工作流状态
	RECOMPENSE_WORKFLOW_STATUS("理赔工作流状态"),
	//理赔工作流类型
	RECOMPENSE_WORKFLOW_TYPE("理赔工作流类型"),
	//理赔迁移工作流类型
	REC_WORKFLOW_TYPE("理赔迁移工作流类型"),
	//代收类型
	REFUND_TYPE("代收类型"),
	//上报编号
	REPORT_NUM("上报编号"),
	//上报类型
	REPORT_TYPE("上报类型"),
	//解决情况
	RESOLVE_CASE("解决情况"),
	//延时申请
	SATISFACTION_DEGREE("延时申请"),
	//散客类型
	SCATTERCUST_TYPE("散客类型"),
	//日程状态
	SCHEDULE_STATUS("日程状态"),
	//二级行业
	SECOND_TRADE("二级行业"),
	//减免类型
	SERVICERECOVERY_REDUCTION_TYPE("减免类型"),
	//申请状态
	SERVICE_RECOVERY_AAPLY_TYPE("申请状态"),
	//客户类型
	SERVICE_RECOVERY_CUSTOMER_TYPE("客户类型"),
	//签收单
	SIGNBILL("签收单"),
	//公告类型
	SPECIALDAY_TYPE("公告类型"),
	//问卷使用范围
	SURVEY_RANGE("问卷使用范围"),
	//问卷状态
	SURVEY_STATUS("问卷状态"),
	//目标级别(会员降级列表)
	TARGET_GRAD_DOWN("目标级别(会员降级列表)"),
	//目标级别(会员升级列表)
	TARGET_GRAD_UP("目标级别(会员升级列表)"),
	//任务属性类型
	TASKPROPERTIES_TYPE("任务属性类型"),
	//任务属性
	TASK_PROPERTY("任务属性"),
	//待办事宜
	TASK_TYPE("待办事宜"),
	//测试哈哈
	TEST("测试哈哈"),
	//跟踪方式
	TRACE_WAY("跟踪方式"),
	//行业
	TRADE("行业"),
	//运输类型
	TRANS_TYPE("运输类型"),
	//用车车型
	TRUCK_TYPE("用车车型"),
	//大客户审批类型
	TYPE_APPROVAL("大客户审批类型"),
	//预警状态
	WARNSTATUS("预警状态"),
	//工作流类型
	WORKFLOWTYPE("工作流类型"),
	//工作流配置
	WORKFLOW_CONFIG("工作流配置"),
	//工作流名称
	WORKFLOW_NAME("工作流名称"),
	//流程状态
	WORKFLOW_STATE("流程状态"),
	//工作流类型
	WORKFLOW_TYPE("工作流类型"),
	//工单来源
	WORK_SINGLE_SOURCE("工单来源");
	private String value;

	private DataHeadTypeEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

}
