//PACKAGE COM.DEPPON.CRM.MODULE.CUSTOMER.WORKFLOW;
//
//IMPORT JAVA.UTIL.HASHMAP;
//IMPORT JAVA.UTIL.MAP;
//IMPORT JAVA.UTIL.SET;
//
//IMPORT ORG.JUNIT.BEFORE;
//IMPORT ORG.JUNIT.TEST;
//
//IMPORT COM.DEPPON.CRM.MODULE.AUTHORIZATION.SHARED.DOMAIN.USER;
//IMPORT COM.DEPPON.CRM.MODULE.CUSTOMER.SHARED.DOMAIN.CONSTANT;
//IMPORT COM.DEPPON.CRM.MODULE.ORGANIZATION.SHARED.DOMAIN.DEPARTMENT;
//IMPORT COM.DEPPON.CRM.MODULE.ORGANIZATION.SHARED.DOMAIN.EMPLOYEE;
//IMPORT COM.DEPPON.FOSS.FRAMEWORK.SERVER.CONTEXT.USERCONTEXT;
//
//PUBLIC CLASS CONTACTVARYTEST {
//	
//PRIVATE WORKFLOWTESTUTIL WFUTIL;
//	
//	
//	@BEFORE
//	PUBLIC VOID SETUP() {
//		WFUTIL = NEW WORKFLOWTESTUTIL("CONTACTVARY"); 
//	}
//	
//	@TEST
//	PUBLIC VOID TESTCONTACTVARYWORK(){
//		//TEST_1006  测试角色
//		
//		MAP MAP = NEW HASHMAP();
//		MAP.PUT("APPID", "123");
//		MAP.PUT("FROMDEPTID", "1111");
//		MAP.PUT("TODEPTID", "1111");
//		LONG WORKFLOWID = -1;
//		
//		STRING USERID = CONSTANT.NEIGHBORHOOD;
//		
//		WORKFLOWID = WFUTIL.ININTWORKFLOW(MAP);
//		WFUTIL.DOACTION(USERID, WORKFLOWID, CONSTANT.CONTACTVARYWK_PASS, NEW HASHMAP());
//		WFUTIL.ASSERTWORKFLOWEND(WORKFLOWID);
//		
//		WORKFLOWID = WFUTIL.ININTWORKFLOW(MAP);
//		WFUTIL.DOACTION(USERID, WORKFLOWID, CONSTANT.CONTACTVARYWK_NOPASS, NEW HASHMAP());
//		WFUTIL.ASSERTWORKFLOWEND(WORKFLOWID);
//	}
//
//	PRIVATE VOID INITUSER() {
//		//TEST_1006  测试角色
//
////		STRING DEPT = "TEST";
//		SET<STRING> ROLES = ROLETEST.GETRULES("1006");
//		
//		USER USER = NEW USER();
//		EMPLOYEE EMPCODE = NEW EMPLOYEE();
//		DEPARTMENT DEPTID = NEW DEPARTMENT();
//		DEPTID.SETID(DEPT);
//		EMPCODE.SETDEPTID(DEPTID);
//		USER.SETROLEIDS(ROLES);
//		USER.SETEMPCODE(EMPCODE);
//		USERCONTEXT.SETCURRENTUSER(USER);
//	}
//
//	
//	
//}
