package com.deppon.crm.module.interfaces.cc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.deppon.crm.module.interfaces.cc.domain.BusinessOpportunityIfexistRequest;
import com.deppon.crm.module.interfaces.cc.domain.BusinessOpportunityIfexistResponse;
import com.deppon.crm.module.interfaces.cc.domain.CommException;
import com.deppon.crm.module.interfaces.cc.domain.CreateCallCenterCustomerRequest;
import com.deppon.crm.module.interfaces.cc.domain.CreateCallCenterCustomerResponse;
import com.deppon.crm.module.interfaces.cc.domain.ESBHeader;
import com.deppon.crm.module.interfaces.cc.domain.MarketingInfoAddRequest;
import com.deppon.crm.module.interfaces.cc.domain.MarketingInfoAddResponse;
import com.deppon.crm.module.interfaces.cc.domain.MarketingInfoQueryDetailRequest;
import com.deppon.crm.module.interfaces.cc.domain.MarketingInfoQueryDetailResponse;
import com.deppon.crm.module.interfaces.cc.domain.MarketingInfoQueryRequest;
import com.deppon.crm.module.interfaces.cc.domain.MarketingInfoQueryResponse;
import com.deppon.crm.module.interfaces.cc.domain.ObjectFactory;
import com.deppon.crm.module.interfaces.cc.domain.RecallPlanRequest;
import com.deppon.crm.module.interfaces.cc.domain.RecallPlanResponse;
import com.deppon.crm.module.interfaces.cc.domain.UpdateCallCenterCustomerRequest;
import com.deppon.crm.module.interfaces.cc.domain.UpdateCallCenterCustomerResponse;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2014-04-09T17:52:27.921+08:00
 * Generated source version: 2.7.3
 *
 */
@WebService(targetNamespace = "http://www.deppon.com/crm/interface/CallcenterToCrmService", name = "ICallcenterToCrmService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ICallcenterToCrmService {

    @WebResult(name = "marketingInfoQueryResponse", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CCToCrmService/queryMarketingInfo")
    public MarketingInfoQueryResponse queryMarketingInfo(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "marketingInfoQueryRequest", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain")
        MarketingInfoQueryRequest request
    ) throws CommException;

    @WebResult(name = "marketingInfoAddResponse", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CCToCrmService/sendMarketingInfo")
    public MarketingInfoAddResponse sendMarketingInfo(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "marketingInfoAddRequest", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain")
        MarketingInfoAddRequest request
    ) throws CommException;

    @WebResult(name = "updateCallCenterCustomerResponse", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CCToCrmService/updateCustomerInfo")
    public UpdateCallCenterCustomerResponse updateCustomerInfo(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "updateCallCenterCustomerRequest", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain")
        UpdateCallCenterCustomerRequest request
    ) throws CommException;

    @WebResult(name = "marketingInfoQueryDetailResponse", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CCToCrmService/queryMarketingDetailInfo")
    public MarketingInfoQueryDetailResponse queryMarketingDetailInfo(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "marketingInfoQueryDetailRequest", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain")
        MarketingInfoQueryDetailRequest request
    ) throws CommException;

    @WebResult(name = "recallPlanResponse", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CCToCrmService/sendRecallPlan")
    public RecallPlanResponse sendRecallPlan(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "recallPlanRequest", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain")
        RecallPlanRequest request
    ) throws CommException;

    @WebResult(name = "createCallCenterCustomerResponse", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CCToCrmService/createCustomerInfo")
    public CreateCallCenterCustomerResponse createCustomerInfo(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "createCallCenterCustomerRequest", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain")
        CreateCallCenterCustomerRequest request
    ) throws CommException;

    @WebResult(name = "businessOpportunityIfexistResponse", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CCToCrmService/validateBusinessOpportunity")
    public BusinessOpportunityIfexistResponse validateBusinessOpportunity(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "businessOpportunityIfexistRequest", targetNamespace = "http://www.deppon.com/crm/inteface/cc/domain")
        BusinessOpportunityIfexistRequest request
    ) throws CommException;
}
