package com.deppon.crm.module.client.sync.cc;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.deppon.crm.module.client.sync.domain.CustTransationOperation.OperationFlg;

public class TCustAccountOperation implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3063354567189488669L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private BigDecimal fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FCREATEUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private BigDecimal fcreateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FCREATEDEPTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private BigDecimal fcreatedeptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FCREATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private Date fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private BigDecimal flastupdateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEDEPTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private BigDecimal flastupdatedeptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private Date flastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBANK
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FISDEFAULTACCOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fisdefaultaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FCOUNTNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fcountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCEID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fbankprovinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBANKAREA
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fbankarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBANKCITYID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fbankcityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMAN
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String ffinancelinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FLINKMANMOBILE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String flinkmanmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fsubbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBANKACCOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fbankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FRELATION
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String frelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBELONGCUSTOM
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private BigDecimal fbelongcustom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FSTATUS
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private BigDecimal fstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FACCOUNTNATURE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String faccountnature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FACCOUNTUSE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String faccountuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FLINKMANPHONE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String flinkmanphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBANKID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fbankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAMEID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fsubbanknameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMANID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private BigDecimal ffinancelinkmanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCENAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fbankprovincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVELOP.T_CUST_ACCOUNT.FBANKCITYNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    private String fbankcityname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FID
     *
     * @param fid the value for DEVELOP.T_CUST_ACCOUNT.FID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFid(BigDecimal fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FCREATEUSERID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FCREATEUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FCREATEUSERID
     *
     * @param fcreateuserid the value for DEVELOP.T_CUST_ACCOUNT.FCREATEUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcreateuserid(BigDecimal fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FCREATEDEPTID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FCREATEDEPTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFcreatedeptid() {
        return fcreatedeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FCREATEDEPTID
     *
     * @param fcreatedeptid the value for DEVELOP.T_CUST_ACCOUNT.FCREATEDEPTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcreatedeptid(BigDecimal fcreatedeptid) {
        this.fcreatedeptid = fcreatedeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FCREATETIME
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FCREATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public Date getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FCREATETIME
     *
     * @param fcreatetime the value for DEVELOP.T_CUST_ACCOUNT.FCREATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcreatetime(Date fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEUSERID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFlastupdateuserid() {
        return flastupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEUSERID
     *
     * @param flastupdateuserid the value for DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlastupdateuserid(BigDecimal flastupdateuserid) {
        this.flastupdateuserid = flastupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEDEPTID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEDEPTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFlastupdatedeptid() {
        return flastupdatedeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEDEPTID
     *
     * @param flastupdatedeptid the value for DEVELOP.T_CUST_ACCOUNT.FLASTUPDATEDEPTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlastupdatedeptid(BigDecimal flastupdatedeptid) {
        this.flastupdatedeptid = flastupdatedeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATETIME
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FLASTUPDATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public Date getFlastupdatetime() {
        return flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FLASTUPDATETIME
     *
     * @param flastupdatetime the value for DEVELOP.T_CUST_ACCOUNT.FLASTUPDATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlastupdatetime(Date flastupdatetime) {
        this.flastupdatetime = flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANK
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBANK
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbank() {
        return fbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANK
     *
     * @param fbank the value for DEVELOP.T_CUST_ACCOUNT.FBANK
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbank(String fbank) {
        this.fbank = fbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FISDEFAULTACCOUNT
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FISDEFAULTACCOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFisdefaultaccount() {
        return fisdefaultaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FISDEFAULTACCOUNT
     *
     * @param fisdefaultaccount the value for DEVELOP.T_CUST_ACCOUNT.FISDEFAULTACCOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFisdefaultaccount(String fisdefaultaccount) {
        this.fisdefaultaccount = fisdefaultaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FCOUNTNAME
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FCOUNTNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFcountname() {
        return fcountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FCOUNTNAME
     *
     * @param fcountname the value for DEVELOP.T_CUST_ACCOUNT.FCOUNTNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcountname(String fcountname) {
        this.fcountname = fcountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCEID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCEID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbankprovinceid() {
        return fbankprovinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCEID
     *
     * @param fbankprovinceid the value for DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCEID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbankprovinceid(String fbankprovinceid) {
        this.fbankprovinceid = fbankprovinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKAREA
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBANKAREA
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbankarea() {
        return fbankarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKAREA
     *
     * @param fbankarea the value for DEVELOP.T_CUST_ACCOUNT.FBANKAREA
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbankarea(String fbankarea) {
        this.fbankarea = fbankarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKCITYID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBANKCITYID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbankcityid() {
        return fbankcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKCITYID
     *
     * @param fbankcityid the value for DEVELOP.T_CUST_ACCOUNT.FBANKCITYID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbankcityid(String fbankcityid) {
        this.fbankcityid = fbankcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMAN
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMAN
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFfinancelinkman() {
        return ffinancelinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMAN
     *
     * @param ffinancelinkman the value for DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMAN
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFfinancelinkman(String ffinancelinkman) {
        this.ffinancelinkman = ffinancelinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FLINKMANMOBILE
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FLINKMANMOBILE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFlinkmanmobile() {
        return flinkmanmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FLINKMANMOBILE
     *
     * @param flinkmanmobile the value for DEVELOP.T_CUST_ACCOUNT.FLINKMANMOBILE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlinkmanmobile(String flinkmanmobile) {
        this.flinkmanmobile = flinkmanmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAME
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFsubbankname() {
        return fsubbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAME
     *
     * @param fsubbankname the value for DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFsubbankname(String fsubbankname) {
        this.fsubbankname = fsubbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKACCOUNT
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBANKACCOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbankaccount() {
        return fbankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKACCOUNT
     *
     * @param fbankaccount the value for DEVELOP.T_CUST_ACCOUNT.FBANKACCOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbankaccount(String fbankaccount) {
        this.fbankaccount = fbankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FRELATION
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FRELATION
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFrelation() {
        return frelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FRELATION
     *
     * @param frelation the value for DEVELOP.T_CUST_ACCOUNT.FRELATION
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFrelation(String frelation) {
        this.frelation = frelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBELONGCUSTOM
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBELONGCUSTOM
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFbelongcustom() {
        return fbelongcustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBELONGCUSTOM
     *
     * @param fbelongcustom the value for DEVELOP.T_CUST_ACCOUNT.FBELONGCUSTOM
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbelongcustom(BigDecimal fbelongcustom) {
        this.fbelongcustom = fbelongcustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FSTATUS
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FSTATUS
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FSTATUS
     *
     * @param fstatus the value for DEVELOP.T_CUST_ACCOUNT.FSTATUS
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFstatus(BigDecimal fstatus) {
        this.fstatus = fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FACCOUNTNATURE
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FACCOUNTNATURE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFaccountnature() {
        return faccountnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FACCOUNTNATURE
     *
     * @param faccountnature the value for DEVELOP.T_CUST_ACCOUNT.FACCOUNTNATURE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFaccountnature(String faccountnature) {
        this.faccountnature = faccountnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FACCOUNTUSE
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FACCOUNTUSE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFaccountuse() {
        return faccountuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FACCOUNTUSE
     *
     * @param faccountuse the value for DEVELOP.T_CUST_ACCOUNT.FACCOUNTUSE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFaccountuse(String faccountuse) {
        this.faccountuse = faccountuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FLINKMANPHONE
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FLINKMANPHONE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFlinkmanphone() {
        return flinkmanphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FLINKMANPHONE
     *
     * @param flinkmanphone the value for DEVELOP.T_CUST_ACCOUNT.FLINKMANPHONE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlinkmanphone(String flinkmanphone) {
        this.flinkmanphone = flinkmanphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBANKID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbankid() {
        return fbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKID
     *
     * @param fbankid the value for DEVELOP.T_CUST_ACCOUNT.FBANKID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbankid(String fbankid) {
        this.fbankid = fbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAMEID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAMEID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFsubbanknameid() {
        return fsubbanknameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAMEID
     *
     * @param fsubbanknameid the value for DEVELOP.T_CUST_ACCOUNT.FSUBBANKNAMEID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFsubbanknameid(String fsubbanknameid) {
        this.fsubbanknameid = fsubbanknameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMANID
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMANID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFfinancelinkmanid() {
        return ffinancelinkmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMANID
     *
     * @param ffinancelinkmanid the value for DEVELOP.T_CUST_ACCOUNT.FFINANCELINKMANID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFfinancelinkmanid(BigDecimal ffinancelinkmanid) {
        this.ffinancelinkmanid = ffinancelinkmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCENAME
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCENAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbankprovincename() {
        return fbankprovincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCENAME
     *
     * @param fbankprovincename the value for DEVELOP.T_CUST_ACCOUNT.FBANKPROVINCENAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbankprovincename(String fbankprovincename) {
        this.fbankprovincename = fbankprovincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKCITYNAME
     *
     * @return the value of DEVELOP.T_CUST_ACCOUNT.FBANKCITYNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbankcityname() {
        return fbankcityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_ACCOUNT.FBANKCITYNAME
     *
     * @param fbankcityname the value for DEVELOP.T_CUST_ACCOUNT.FBANKCITYNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbankcityname(String fbankcityname) {
        this.fbankcityname = fbankcityname;
    }


	public OperationFlg getOperationFlg() {
		return operationFlg;
	}

	public void setOperationFlg(OperationFlg operationFlg) {
		this.operationFlg = operationFlg;
	}

	private OperationFlg operationFlg;
}
