package com.deppon.crm.module.interfaces.uums;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.deppon.crm.module.interfaces.uums.ws.ESBHeader;
import com.deppon.crm.module.interfaces.uums.ws.ObjectFactory;
import com.deppon.crm.module.interfaces.uums.ws.SendCompanyInfoRequest;
import com.deppon.crm.module.interfaces.uums.ws.SendCompanyInfoResponse;
import com.deppon.crm.module.interfaces.uums.ws.SyncCompanyInfosFault;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-29T18:35:59.796+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://www.deppon.com/crm/crmService", name = "UumsToCrmService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UumsToCrmService {

    @WebResult(name = "SendCompanyInfoResponse", targetNamespace = "http://www.deppon.com/crm/inteface/domain/companymanagement", partName = "syncCompanyInfosResponse")
    @WebMethod(action = "http://www.deppon.com/crm/crmService/NewOperation")
    public SendCompanyInfoResponse syncCompanyInfos(
        @WebParam(partName = "syncCompanyInfosRequest", name = "SendCompanyInfoRequest", targetNamespace = "http://www.deppon.com/crm/inteface/domain/companymanagement")
        SendCompanyInfoRequest syncCompanyInfosRequest,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader
    ) throws SyncCompanyInfosFault;
}
