
//-------------init role

DELETE FROM T_AUTH_ROLE WHERE FID=3;
DELETE FROM T_AUTH_USERROLE where froleid=3;
INSERT INTO T_AUTH_ROLE(
    FID,
    FROLENAME,
    FROLEDESC,
    FCREATEUSERID,
    FCREATETIME,
    FLASTMODIFYUSERID,
    FLASTUPDATETIME
)VALUES(
    3,
    '理赔经理', 
    '理赔经理角色',
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD'),
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD')
);
DELETE FROM T_AUTH_ROLE WHERE FID=4;
DELETE FROM T_AUTH_USERROLE where froleid=4;
INSERT INTO T_AUTH_ROLE(
    FID,
    FROLENAME,
    FROLEDESC,
    FCREATEUSERID,
    FCREATETIME,
    FLASTMODIFYUSERID,
    FLASTUPDATETIME
)VALUES(
    4,
    '理赔专员', 
    '理赔专员角色',
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD'),
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD')
);
DELETE FROM T_AUTH_ROLE WHERE FID=5;
DELETE FROM T_AUTH_USERROLE where froleid=5;
INSERT INTO T_AUTH_ROLE(
    FID,
    FROLENAME,
    FROLEDESC,
    FCREATEUSERID,
    FCREATETIME,
    FLASTMODIFYUSERID,
    FLASTUPDATETIME
)VALUES(
    5,
    '理赔收银员', 
    '理赔收银员角色',
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD'),
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD')
);

DELETE FROM T_AUTH_ROLE WHERE FID=6;
DELETE FROM T_AUTH_USERROLE where froleid=6;
INSERT INTO T_AUTH_ROLE(
    FID,
    FROLENAME,
    FROLEDESC,
    FCREATEUSERID,
    FCREATETIME,
    FLASTMODIFYUSERID,
    FLASTUPDATETIME
)VALUES(
    6,
    'OA工作流审批用户', 
    'OA工作流审批用户角色',
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD'),
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD')
);

DELETE FROM T_AUTH_ROLE WHERE FID=7;
DELETE FROM T_AUTH_USERROLE where froleid=7;
INSERT INTO T_AUTH_ROLE(
    FID,
    FROLENAME,
    FROLEDESC,
    FCREATEUSERID,
    FCREATETIME,
    FLASTMODIFYUSERID,
    FLASTUPDATETIME
)VALUES(
    7,
    'Erp冲账系统用户', 
    'Erp冲账系统用户角色',
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD'),
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD')
);

DELETE FROM T_AUTH_ROLE WHERE FID=8;
DELETE FROM T_AUTH_USERROLE where froleid=8;
INSERT INTO T_AUTH_ROLE(
    FID,
    FROLENAME,
    FROLEDESC,
    FCREATEUSERID,
    FCREATETIME,
    FLASTMODIFYUSERID,
    FLASTUPDATETIME
)VALUES(
    8,
    '费控系统用户', 
    '费控系统用户角色',
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD'),
    1,
    TO_DATE('2012-04-07', 'YYYY-MM-DD')
);
//---------init user

DELETE FROM T_AUTH_USERROLE
 WHERE FROLEID = 3
   AND FUSERID = 229492;
INSERT INTO T_AUTH_USERROLE
  (FID, FROLEID, FUSERID)
VALUES
  (USER_ROLE_SEQ.NEXTVAL, 3, 229492);

DELETE FROM T_AUTH_USERROLE
 WHERE FROLEID = 4
   AND FUSERID = 21935;
INSERT INTO T_AUTH_USERROLE
  (FID, FROLEID, FUSERID)
VALUES
  (USER_ROLE_SEQ.NEXTVAL, 4, 21935);

DELETE FROM T_AUTH_USERROLE
 WHERE FROLEID = 5
   AND FUSERID = 273139;
INSERT INTO T_AUTH_USERROLE
  (FID, FROLEID, FUSERID)
VALUES
  (USER_ROLE_SEQ.NEXTVAL, 5, 273139);

DELETE FROM T_AUTH_USERROLE
 WHERE FROLEID = 6
   AND FUSERID = 26700;
INSERT INTO T_AUTH_USERROLE
  (FID, FROLEID, FUSERID)
VALUES
  (USER_ROLE_SEQ.NEXTVAL, 6, 26700);

DELETE FROM T_AUTH_USERROLE
 WHERE FROLEID = 7
   AND FUSERID = 221791;
INSERT INTO T_AUTH_USERROLE
  (FID, FROLEID, FUSERID)
VALUES
  (USER_ROLE_SEQ.NEXTVAL, 7, 221791);

DELETE FROM T_AUTH_USERROLE
 WHERE FROLEID = 8
   AND FUSERID = 234443;
INSERT INTO T_AUTH_USERROLE
  (FID, FROLEID, FUSERID)
VALUES
  (USER_ROLE_SEQ.NEXTVAL, 8, 234443);

UPDATE T_AUTH_USER U
   SET U.FSTATUS = 1, u.fpassword = 'NDscSj6nIbLWQPyHANsPNg=='
 WHERE U.FID IN（26700, 221791, 234443, 229492, 21935, 273139）;

SELECT U.FID, U.FEMPCODE, E.FEMPNAME, U.FSTATUS, R.FROLEID
  FROM T_AUTH_USER U
 INNER JOIN T_ORG_EMPLOYEE E
    ON U.FEMPCODE = E.FEMPCODE
 INNER JOIN (SELECT *
               FROM T_AUTH_USERROLE
              WHERE FROLEID IN (3, 4, 5, 6, 7, 8)) R
    ON U.FID = R.FUSERID
 WHERE U.FID IN（26700, 221791, 234443, 229492, 21935, 273139）;

INSERT INTO T_REC_ROLEDEPARTMENT
  (FID, FUSERID, FROLEID, FDEPTID) VALUES（SEQ_ID_ROLEDEPT.NEXTVAL, 21935, 4, 10051）;
