//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.29 at 04:46:52 下午 CST 
//


package com.deppon.crm.module.interfaces.foss.domain.domainInfo;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MotorcadeInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MotorcadeInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unifiedCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isTopMotorcade" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modifyTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MotorcadeInfo", propOrder = {
    "id",
    "unifiedCode",
    "isTopMotorcade",
    "modifyTime"
})
public class MotorcadeInfo {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String unifiedCode;
    @XmlElement(required = true)
    protected String isTopMotorcade;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date modifyTime;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the unifiedCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnifiedCode() {
        return unifiedCode;
    }

    /**
     * Sets the value of the unifiedCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnifiedCode(String value) {
        this.unifiedCode = value;
    }

    /**
     * Gets the value of the isTopMotorcade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTopMotorcade() {
        return isTopMotorcade;
    }

    /**
     * Sets the value of the isTopMotorcade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTopMotorcade(String value) {
        this.isTopMotorcade = value;
    }

    /**
     * Gets the value of the modifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * Sets the value of the modifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifyTime(Date value) {
        this.modifyTime = value;
    }

}
