//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.29 at 04:46:52 下午 CST 
//


package com.deppon.crm.module.interfaces.foss.domain.domainInfo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.deppon.crm.module.interfaces.foss.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    public final static QName _SyncMotorcadeRequest_QNAME = new QName("http://www.deppon.com/crm/inteface/domain/", "SyncMotorcadeRequest");
    public final static QName _SyncMotorcadeResponse_QNAME = new QName("http://www.deppon.com/crm/inteface/domain/", "SyncMotorcadeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deppon.crm.module.interfaces.foss.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SyncMotorcadeResponse }
     * 
     */
    public SyncMotorcadeResponse createSyncMotorcadeResponse() {
        return new SyncMotorcadeResponse();
    }

    /**
     * Create an instance of {@link SyncMotorcadeRequest }
     * 
     */
    public SyncMotorcadeRequest createSyncMotorcadeRequest() {
        return new SyncMotorcadeRequest();
    }

    /**
     * Create an instance of {@link ResultInfo }
     * 
     */
    public ResultInfo createResultInfo() {
        return new ResultInfo();
    }

    /**
     * Create an instance of {@link MotorcadeInfo }
     * 
     */
    public MotorcadeInfo createMotorcadeInfo() {
        return new MotorcadeInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncMotorcadeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/crm/inteface/domain/", name = "SyncMotorcadeRequest")
    public JAXBElement<SyncMotorcadeRequest> createSyncMotorcadeRequest(SyncMotorcadeRequest value) {
        return new JAXBElement<SyncMotorcadeRequest>(_SyncMotorcadeRequest_QNAME, SyncMotorcadeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncMotorcadeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/crm/inteface/domain/", name = "SyncMotorcadeResponse")
    public JAXBElement<SyncMotorcadeResponse> createSyncMotorcadeResponse(SyncMotorcadeResponse value) {
        return new JAXBElement<SyncMotorcadeResponse>(_SyncMotorcadeResponse_QNAME, SyncMotorcadeResponse.class, null, value);
    }

}
