//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.29 at 04:46:52 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deppon.com/crm/inteface/domain/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.deppon.crm.module.interfaces.foss.domain.domainInfo;
