package com.deppon.crm.module.interfaces.foss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;

import com.deppon.crm.module.interfaces.foss.domain.BackFreightCheckRequest;
import com.deppon.crm.module.interfaces.foss.domain.BackFreightCheckResponse;
import com.deppon.crm.module.interfaces.foss.domain.CommException;
import com.deppon.crm.module.interfaces.foss.domain.CouponStateRequest;
import com.deppon.crm.module.interfaces.foss.domain.CouponStateResponse;
import com.deppon.crm.module.interfaces.foss.domain.ESBHeader;
import com.deppon.crm.module.interfaces.foss.domain.ModifyOrderLockInfoRequest;
import com.deppon.crm.module.interfaces.foss.domain.ModifyOrderLockInfoResponse;
import com.deppon.crm.module.interfaces.foss.domain.QueryClaimbillRequest;
import com.deppon.crm.module.interfaces.foss.domain.QueryClaimbillResponse;
import com.deppon.crm.module.interfaces.foss.domain.QueryOrderListRequest;
import com.deppon.crm.module.interfaces.foss.domain.QueryOrderListResponse;
import com.deppon.crm.module.interfaces.foss.domain.SearchOrderRequest;
import com.deppon.crm.module.interfaces.foss.domain.SearchOrderResponse;
import com.deppon.crm.module.interfaces.foss.domain.ValidateCouponRequest;
import com.deppon.crm.module.interfaces.foss.domain.ValidateCouponResponse;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-11-30T11:16:19.890+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://www.deppon.com/crm/interface/CrmService", name = "fossToCrmService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FossToCrmService {

    @WebResult(name = "backFreightCheckResponse", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/backFreightCheck")
    public BackFreightCheckResponse backFreightCheck(
        @WebParam(partName = "request", name = "backFreightCheckRequest", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain")
        BackFreightCheckRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader
    ) throws CommException;

    @WebResult(name = "queryOrderListResponse", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain", partName = "queryOrderListResponse")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/queryOrder")
    public QueryOrderListResponse queryOrder(
        @WebParam(partName = "queryOrderListRequest", name = "queryOrderListRequest", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain")
        QueryOrderListRequest queryOrderListRequest,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader
    ) throws CommException;

    @WebResult(name = "couponStateResponse", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/effectCouponState")
    public CouponStateResponse effectCouponState(
        @WebParam(partName = "request", name = "couponStateRequest", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain")
        CouponStateRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader
    ) throws CommException;

    @WebResult(name = "validateCouponResponse", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain", partName = "Response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/validateCoupon")
    public ValidateCouponResponse validateCoupon(
        @WebParam(partName = "request", name = "validateCouponRequest", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain")
        ValidateCouponRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader
    ) throws CommException;

    @WebResult(name = "searchOrderResponse", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain", partName = "searchOrderResponse")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/searchOrder")
    public SearchOrderResponse searchOrder(
        @WebParam(partName = "searchOrderRequest", name = "searchOrderRequest", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain")
        SearchOrderRequest searchOrderRequest,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader
    ) throws CommException;
    
    @WebResult(name = "query_claimbillResponse", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/queryClaimbill")
    public QueryClaimbillResponse queryClaimbill(
        @WebParam(partName = "request", name = "query_claimbillRequest", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain")
        QueryClaimbillRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader
    ) throws CommException;
    
    
    
    /**
	 * 订单锁屏
	 * 
	 * @param esbHeader
	 * @param request
	 * @return returns
	 *         com.deppon.crm.module.interfaces.foss.order.ModifyOrderLockInfoResponse
	 * @throws CommException
	 */
	@WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/modifyOrderLockInfo")
	@WebResult(name = "ModifyOrderLockInfoResponse", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain", partName = "response")
	public ModifyOrderLockInfoResponse modifyOrderLockInfo(
			@WebParam(name = "ModifyOrderLockInfoRequest", targetNamespace = "http://www.deppon.com/crm/inteface/foss/domain", partName = "request") ModifyOrderLockInfoRequest request,
			@WebParam(name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true, mode = WebParam.Mode.INOUT, partName = "esbHeader") Holder<ESBHeader> esbHeader)
			throws CommException;

}
