package com.deppon.erp.waybill;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-26T14:34:45.149+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "Erp2esbServiceImplService", 
                  wsdlLocation = "http://192.168.17.41:8080/eas2fin/services/erp2esbService?wsdl",
                  targetNamespace = "http://impl.service.cms.ws.deppon.com/") 
public class Erp2EsbServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.cms.ws.deppon.com/", "Erp2esbServiceImplService");
    public final static QName Erp2EsbServiceImplPort = new QName("http://impl.service.cms.ws.deppon.com/", "Erp2esbServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.17.41:8080/eas2fin/services/erp2esbService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Erp2EsbServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.17.41:8080/eas2fin/services/erp2esbService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Erp2EsbServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Erp2EsbServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Erp2EsbServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IErp2EsbService
     */
    @WebEndpoint(name = "Erp2esbServiceImplPort")
    public IErp2EsbService getErp2EsbServiceImplPort() {
        return super.getPort(Erp2EsbServiceImplPort, IErp2EsbService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IErp2EsbService
     */
    @WebEndpoint(name = "Erp2esbServiceImplPort")
    public IErp2EsbService getErp2EsbServiceImplPort(WebServiceFeature... features) {
        return super.getPort(Erp2EsbServiceImplPort, IErp2EsbService.class, features);
    }

}
