package com.deppon.erp.waybill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-26T14:34:45.149+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.cms.ws.deppon.com/", name = "IErp2esbService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IErp2EsbService {

    @WebResult(name = "addReceiveGoodsBillResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "addReceiveGoodsBillResponse")
    @WebMethod
    public boolean addReceiveGoodsBill(
        @WebParam(partName = "addReceiveGoodsBill", name = "addReceiveGoodsBill", targetNamespace = "http://service.cms.ws.deppon.com/")
        ReceiveGoodsBill addReceiveGoodsBill
    ) throws ERPBusinessException_Exception;
}
