package com.deppon.erp.waybill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-03-18T11:32:24.015+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.cms.ws.deppon.com/", name = "IErp2crmService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IErp2CrmService {

    @WebResult(name = "linkWayBillAndOrderBillResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "linkWayBillAndOrderBillResponse")
    @WebMethod
    public boolean linkWayBillAndOrderBill(
        @WebParam(partName = "wayBillNumBeofre", name = "wayBillNumBeofre", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String wayBillNumBeofre,
        @WebParam(partName = "wayBillNumAfter", name = "wayBillNumAfter", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String wayBillNumAfter,
        @WebParam(partName = "orderBillNum", name = "orderBillNum", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String orderBillNum
    ) throws ERPBusinessException_Exception;

    @WebResult(name = "queryWayBillNotSignResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryWayBillNotSignResponse")
    @WebMethod
    public WayBillNotSign queryWayBillNotSign(
        @WebParam(partName = "queryWayBillNotSign", name = "queryWayBillNotSign", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String queryWayBillNotSign
    ) throws ERPBusinessException_Exception;

    @WebResult(name = "queryWayBillSimpleResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryWayBillSimpleResponse")
    @WebMethod
    public WayBillSimpleArray queryWayBillSimple(
        @WebParam(partName = "linkManNum", name = "linkManNum", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String linkManNum,
        @WebParam(partName = "startDate", name = "startDate", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.util.Date startDate,
        @WebParam(partName = "endDate", name = "endDate", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.util.Date endDate
    ) throws ERPBusinessException_Exception;

    @WebResult(name = "queryNear3MonthAmountResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryNear3MonthAmountResponse")
    @WebMethod
    public java.math.BigDecimal queryNear3MonthAmount(
        @WebParam(partName = "queryNear3MonthAmount", name = "queryNear3MonthAmount", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String queryNear3MonthAmount
    ) throws ERPBusinessException_Exception;

    @WebResult(name = "queryCustAmountResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryCustAmountResponse")
    @WebMethod
    public CustAmountArray queryCustAmount(
        @WebParam(partName = "custMobile", name = "custMobile", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String custMobile,
        @WebParam(partName = "cust", name = "cust", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String cust,
        @WebParam(partName = "custPhone", name = "custPhone", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String custPhone
    ) throws ERPBusinessException_Exception;

    @WebResult(name = "queryWayBillRecompenseResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryWayBillRecompenseResponse")
    @WebMethod
    public WayBillRecompense queryWayBillRecompense(
        @WebParam(partName = "queryWayBillRecompense", name = "queryWayBillRecompense", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String queryWayBillRecompense
    ) throws ERPBusinessException_Exception;

    @WebResult(name = "queryWayBillResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryWayBillResponse")
    @WebMethod
    public WayBill queryWayBill(
        @WebParam(partName = "queryWayBill", name = "queryWayBill", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String queryWayBill
    ) throws ERPBusinessException_Exception;

    @WebResult(name = "queryWayBillCustomerResponse", targetNamespace = "http://service.cms.ws.deppon.com/", partName = "queryWayBillCustomerResponse")
    @WebMethod
    public WayBillCustomer queryWayBillCustomer(
        @WebParam(partName = "queryWayBillCustomer", name = "queryWayBillCustomer", targetNamespace = "http://service.cms.ws.deppon.com/")
        java.lang.String queryWayBillCustomer
    ) throws ERPBusinessException_Exception;
}
