package com.deppon.esb.sync;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-30T17:41:06.011+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "SyncDataServiceImplService", 
                  wsdlLocation = "http://localhost:9090/sync?wsdl",
                  targetNamespace = "http://impl.sync.crm.deppon.com/") 
public class SyncDataServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.sync.crm.deppon.com/", "SyncDataServiceImplService");
    public final static QName SyncDataServiceImplPort = new QName("http://impl.sync.crm.deppon.com/", "SyncDataServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/sync?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SyncDataServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/sync?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SyncDataServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SyncDataServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncDataServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ISyncDataService
     */
    @WebEndpoint(name = "SyncDataServiceImplPort")
    public ISyncDataService getSyncDataServiceImplPort() {
        return super.getPort(SyncDataServiceImplPort, ISyncDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISyncDataService
     */
    @WebEndpoint(name = "SyncDataServiceImplPort")
    public ISyncDataService getSyncDataServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SyncDataServiceImplPort, ISyncDataService.class, features);
    }

}
