
package com.deppon.esb.sync;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-30T17:41:05.933+08:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "SyncData", targetNamespace = "http://sync.crm.deppon.com/")
public class SyncDataException extends Exception {
    
    private com.deppon.esb.sync.SyncData syncData;

    public SyncDataException() {
        super();
    }
    
    public SyncDataException(String message) {
        super(message);
    }
    
    public SyncDataException(String message, Throwable cause) {
        super(message, cause);
    }

    public SyncDataException(String message, com.deppon.esb.sync.SyncData syncData) {
        super(message);
        this.syncData = syncData;
    }

    public SyncDataException(String message, com.deppon.esb.sync.SyncData syncData, Throwable cause) {
        super(message, cause);
        this.syncData = syncData;
    }

    public com.deppon.esb.sync.SyncData getFaultInfo() {
        return this.syncData;
    }
}
